/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.AccessOidcAuthUrlRequest
import com.clientapi.pmg.models.AccessOidcAuthUrlResponse
import com.clientapi.pmg.models.AccessOidcGetOidcResponse
import com.clientapi.pmg.models.AccessOidcLoginRequest
import com.clientapi.pmg.models.AccessOidcLoginResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class AccessOidcApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /access/oidc/auth-url
     * Get the OpenId Connect Authorization Url for the specified realm
     * Get the OpenId Connect Authorization Url for the specified realm.
     * @param accessOidcAuthUrlRequest 
     * @return AccessOidcAuthUrlResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessOidcAuthUrl(accessOidcAuthUrlRequest: AccessOidcAuthUrlRequest) : AccessOidcAuthUrlResponse {
        val localVarResponse = accessOidcAuthUrlWithHttpInfo(accessOidcAuthUrlRequest = accessOidcAuthUrlRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessOidcAuthUrlResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/oidc/auth-url
     * Get the OpenId Connect Authorization Url for the specified realm
     * Get the OpenId Connect Authorization Url for the specified realm.
     * @param accessOidcAuthUrlRequest 
     * @return ApiResponse<AccessOidcAuthUrlResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessOidcAuthUrlWithHttpInfo(accessOidcAuthUrlRequest: AccessOidcAuthUrlRequest) : ApiResponse<AccessOidcAuthUrlResponse?> {
        val localVariableConfig = accessOidcAuthUrlRequestConfig(accessOidcAuthUrlRequest = accessOidcAuthUrlRequest)

        return request<AccessOidcAuthUrlRequest, AccessOidcAuthUrlResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessOidcAuthUrl
     *
     * @param accessOidcAuthUrlRequest 
     * @return RequestConfig
     */
    fun accessOidcAuthUrlRequestConfig(accessOidcAuthUrlRequest: AccessOidcAuthUrlRequest) : RequestConfig<AccessOidcAuthUrlRequest> {
        val localVariableBody = accessOidcAuthUrlRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/oidc/auth-url",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /access/oidc
     * Directory index
     * Directory index.
     * @return AccessOidcGetOidcResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessOidcGetOidc() : AccessOidcGetOidcResponse {
        val localVarResponse = accessOidcGetOidcWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessOidcGetOidcResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/oidc
     * Directory index
     * Directory index.
     * @return ApiResponse<AccessOidcGetOidcResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessOidcGetOidcWithHttpInfo() : ApiResponse<AccessOidcGetOidcResponse?> {
        val localVariableConfig = accessOidcGetOidcRequestConfig()

        return request<Unit, AccessOidcGetOidcResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessOidcGetOidc
     *
     * @return RequestConfig
     */
    fun accessOidcGetOidcRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/oidc",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /access/oidc/login
     * Verify OpenID Connect authorization code and create a ticket
     * Verify OpenID Connect authorization code and create a ticket.
     * @param accessOidcLoginRequest 
     * @return AccessOidcLoginResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessOidcLogin(accessOidcLoginRequest: AccessOidcLoginRequest) : AccessOidcLoginResponse {
        val localVarResponse = accessOidcLoginWithHttpInfo(accessOidcLoginRequest = accessOidcLoginRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessOidcLoginResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/oidc/login
     * Verify OpenID Connect authorization code and create a ticket
     * Verify OpenID Connect authorization code and create a ticket.
     * @param accessOidcLoginRequest 
     * @return ApiResponse<AccessOidcLoginResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessOidcLoginWithHttpInfo(accessOidcLoginRequest: AccessOidcLoginRequest) : ApiResponse<AccessOidcLoginResponse?> {
        val localVariableConfig = accessOidcLoginRequestConfig(accessOidcLoginRequest = accessOidcLoginRequest)

        return request<AccessOidcLoginRequest, AccessOidcLoginResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessOidcLogin
     *
     * @param accessOidcLoginRequest 
     * @return RequestConfig
     */
    fun accessOidcLoginRequestConfig(accessOidcLoginRequest: AccessOidcLoginRequest) : RequestConfig<AccessOidcLoginRequest> {
        val localVariableBody = accessOidcLoginRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/oidc/login",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
