/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.ConfigClusterAddNodeRequest
import com.clientapi.pmg.models.ConfigClusterAddNodeResponse
import com.clientapi.pmg.models.ConfigClusterCreateCreateResponse
import com.clientapi.pmg.models.ConfigClusterGetClusterResponse
import com.clientapi.pmg.models.ConfigClusterJoinRequest
import com.clientapi.pmg.models.ConfigClusterJoinResponse
import com.clientapi.pmg.models.ConfigClusterNodesResponse
import com.clientapi.pmg.models.ConfigClusterStatusResponse
import com.clientapi.pmg.models.ConfigClusterUpdateFingerprintsResponse
import com.clientapi.pmg.models.PmgBoolean
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class ConfigClusterApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /config/cluster/nodes
     * Add an node to the cluster config
     * Add an node to the cluster config.
     * @param configClusterAddNodeRequest 
     * @return ConfigClusterAddNodeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterAddNode(configClusterAddNodeRequest: ConfigClusterAddNodeRequest) : ConfigClusterAddNodeResponse {
        val localVarResponse = configClusterAddNodeWithHttpInfo(configClusterAddNodeRequest = configClusterAddNodeRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterAddNodeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/cluster/nodes
     * Add an node to the cluster config
     * Add an node to the cluster config.
     * @param configClusterAddNodeRequest 
     * @return ApiResponse<ConfigClusterAddNodeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterAddNodeWithHttpInfo(configClusterAddNodeRequest: ConfigClusterAddNodeRequest) : ApiResponse<ConfigClusterAddNodeResponse?> {
        val localVariableConfig = configClusterAddNodeRequestConfig(configClusterAddNodeRequest = configClusterAddNodeRequest)

        return request<ConfigClusterAddNodeRequest, ConfigClusterAddNodeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterAddNode
     *
     * @param configClusterAddNodeRequest 
     * @return RequestConfig
     */
    fun configClusterAddNodeRequestConfig(configClusterAddNodeRequest: ConfigClusterAddNodeRequest) : RequestConfig<ConfigClusterAddNodeRequest> {
        val localVariableBody = configClusterAddNodeRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/cluster/nodes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /config/cluster/create
     * Create initial cluster config with current node as master
     * Create initial cluster config with current node as master.
     * @return ConfigClusterCreateCreateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterCreateCreate() : ConfigClusterCreateCreateResponse {
        val localVarResponse = configClusterCreateCreateWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterCreateCreateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/cluster/create
     * Create initial cluster config with current node as master
     * Create initial cluster config with current node as master.
     * @return ApiResponse<ConfigClusterCreateCreateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterCreateCreateWithHttpInfo() : ApiResponse<ConfigClusterCreateCreateResponse?> {
        val localVariableConfig = configClusterCreateCreateRequestConfig()

        return request<Unit, ConfigClusterCreateCreateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterCreateCreate
     *
     * @return RequestConfig
     */
    fun configClusterCreateCreateRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/cluster/create",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/cluster
     * Directory index
     * Directory index.
     * @return ConfigClusterGetClusterResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterGetCluster() : ConfigClusterGetClusterResponse {
        val localVarResponse = configClusterGetClusterWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterGetClusterResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/cluster
     * Directory index
     * Directory index.
     * @return ApiResponse<ConfigClusterGetClusterResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterGetClusterWithHttpInfo() : ApiResponse<ConfigClusterGetClusterResponse?> {
        val localVariableConfig = configClusterGetClusterRequestConfig()

        return request<Unit, ConfigClusterGetClusterResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterGetCluster
     *
     * @return RequestConfig
     */
    fun configClusterGetClusterRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/cluster",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /config/cluster/join
     * Join local node to an existing cluster
     * Join local node to an existing cluster.
     * @param configClusterJoinRequest 
     * @return ConfigClusterJoinResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterJoin(configClusterJoinRequest: ConfigClusterJoinRequest) : ConfigClusterJoinResponse {
        val localVarResponse = configClusterJoinWithHttpInfo(configClusterJoinRequest = configClusterJoinRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterJoinResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/cluster/join
     * Join local node to an existing cluster
     * Join local node to an existing cluster.
     * @param configClusterJoinRequest 
     * @return ApiResponse<ConfigClusterJoinResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterJoinWithHttpInfo(configClusterJoinRequest: ConfigClusterJoinRequest) : ApiResponse<ConfigClusterJoinResponse?> {
        val localVariableConfig = configClusterJoinRequestConfig(configClusterJoinRequest = configClusterJoinRequest)

        return request<ConfigClusterJoinRequest, ConfigClusterJoinResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterJoin
     *
     * @param configClusterJoinRequest 
     * @return RequestConfig
     */
    fun configClusterJoinRequestConfig(configClusterJoinRequest: ConfigClusterJoinRequest) : RequestConfig<ConfigClusterJoinRequest> {
        val localVariableBody = configClusterJoinRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/cluster/join",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/cluster/nodes
     * Cluster node index
     * Cluster node index.
     * @return ConfigClusterNodesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterNodes() : ConfigClusterNodesResponse {
        val localVarResponse = configClusterNodesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterNodesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/cluster/nodes
     * Cluster node index
     * Cluster node index.
     * @return ApiResponse<ConfigClusterNodesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterNodesWithHttpInfo() : ApiResponse<ConfigClusterNodesResponse?> {
        val localVariableConfig = configClusterNodesRequestConfig()

        return request<Unit, ConfigClusterNodesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterNodes
     *
     * @return RequestConfig
     */
    fun configClusterNodesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/cluster/nodes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/cluster/status
     * Cluster node status
     * Cluster node status.
     * @param listSingleNode List local node if there is no cluster defined. Please note that RSA keys and fingerprint are not valid in that case. (optional)
     * @return ConfigClusterStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterStatus(listSingleNode: PmgBoolean? = null) : ConfigClusterStatusResponse {
        val localVarResponse = configClusterStatusWithHttpInfo(listSingleNode = listSingleNode)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/cluster/status
     * Cluster node status
     * Cluster node status.
     * @param listSingleNode List local node if there is no cluster defined. Please note that RSA keys and fingerprint are not valid in that case. (optional)
     * @return ApiResponse<ConfigClusterStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterStatusWithHttpInfo(listSingleNode: PmgBoolean?) : ApiResponse<ConfigClusterStatusResponse?> {
        val localVariableConfig = configClusterStatusRequestConfig(listSingleNode = listSingleNode)

        return request<Unit, ConfigClusterStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterStatus
     *
     * @param listSingleNode List local node if there is no cluster defined. Please note that RSA keys and fingerprint are not valid in that case. (optional)
     * @return RequestConfig
     */
    fun configClusterStatusRequestConfig(listSingleNode: PmgBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (listSingleNode != null) {
                    put("list_single_node", listOf(listSingleNode.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/cluster/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /config/cluster/update-fingerprints
     * Update API certificate fingerprints (by fetching it via ssh)
     * Update API certificate fingerprints (by fetching it via ssh).
     * @return ConfigClusterUpdateFingerprintsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configClusterUpdateFingerprints() : ConfigClusterUpdateFingerprintsResponse {
        val localVarResponse = configClusterUpdateFingerprintsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigClusterUpdateFingerprintsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/cluster/update-fingerprints
     * Update API certificate fingerprints (by fetching it via ssh)
     * Update API certificate fingerprints (by fetching it via ssh).
     * @return ApiResponse<ConfigClusterUpdateFingerprintsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configClusterUpdateFingerprintsWithHttpInfo() : ApiResponse<ConfigClusterUpdateFingerprintsResponse?> {
        val localVariableConfig = configClusterUpdateFingerprintsRequestConfig()

        return request<Unit, ConfigClusterUpdateFingerprintsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configClusterUpdateFingerprints
     *
     * @return RequestConfig
     */
    fun configClusterUpdateFingerprintsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/cluster/update-fingerprints",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
