/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.ConfigAdminReadAdminSectionResponse
import com.clientapi.pmg.models.ConfigAdminUpdateAdminSectionRequest
import com.clientapi.pmg.models.ConfigAdminUpdateAdminSectionResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class ConfigAdminApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /config/admin
     * Read admin configuration properties
     * Read admin configuration properties.
     * @return ConfigAdminReadAdminSectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAdminReadAdminSection() : ConfigAdminReadAdminSectionResponse {
        val localVarResponse = configAdminReadAdminSectionWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAdminReadAdminSectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/admin
     * Read admin configuration properties
     * Read admin configuration properties.
     * @return ApiResponse<ConfigAdminReadAdminSectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAdminReadAdminSectionWithHttpInfo() : ApiResponse<ConfigAdminReadAdminSectionResponse?> {
        val localVariableConfig = configAdminReadAdminSectionRequestConfig()

        return request<Unit, ConfigAdminReadAdminSectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAdminReadAdminSection
     *
     * @return RequestConfig
     */
    fun configAdminReadAdminSectionRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/admin",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/admin
     * Update admin configuration properties
     * Update admin configuration properties.
     * @param configAdminUpdateAdminSectionRequest  (optional)
     * @return ConfigAdminUpdateAdminSectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAdminUpdateAdminSection(configAdminUpdateAdminSectionRequest: ConfigAdminUpdateAdminSectionRequest? = null) : ConfigAdminUpdateAdminSectionResponse {
        val localVarResponse = configAdminUpdateAdminSectionWithHttpInfo(configAdminUpdateAdminSectionRequest = configAdminUpdateAdminSectionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAdminUpdateAdminSectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/admin
     * Update admin configuration properties
     * Update admin configuration properties.
     * @param configAdminUpdateAdminSectionRequest  (optional)
     * @return ApiResponse<ConfigAdminUpdateAdminSectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAdminUpdateAdminSectionWithHttpInfo(configAdminUpdateAdminSectionRequest: ConfigAdminUpdateAdminSectionRequest?) : ApiResponse<ConfigAdminUpdateAdminSectionResponse?> {
        val localVariableConfig = configAdminUpdateAdminSectionRequestConfig(configAdminUpdateAdminSectionRequest = configAdminUpdateAdminSectionRequest)

        return request<ConfigAdminUpdateAdminSectionRequest, ConfigAdminUpdateAdminSectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAdminUpdateAdminSection
     *
     * @param configAdminUpdateAdminSectionRequest  (optional)
     * @return RequestConfig
     */
    fun configAdminUpdateAdminSectionRequestConfig(configAdminUpdateAdminSectionRequest: ConfigAdminUpdateAdminSectionRequest?) : RequestConfig<ConfigAdminUpdateAdminSectionRequest> {
        val localVariableBody = configAdminUpdateAdminSectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/admin",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
