/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.ConfigSpamquarReadSpamquarSectionResponse
import com.clientapi.pmg.models.ConfigSpamquarUpdateSpamquarSectionRequest
import com.clientapi.pmg.models.ConfigSpamquarUpdateSpamquarSectionResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class ConfigSpamquarApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /config/spamquar
     * Read spamquar configuration properties
     * Read spamquar configuration properties.
     * @return ConfigSpamquarReadSpamquarSectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configSpamquarReadSpamquarSection() : ConfigSpamquarReadSpamquarSectionResponse {
        val localVarResponse = configSpamquarReadSpamquarSectionWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigSpamquarReadSpamquarSectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/spamquar
     * Read spamquar configuration properties
     * Read spamquar configuration properties.
     * @return ApiResponse<ConfigSpamquarReadSpamquarSectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configSpamquarReadSpamquarSectionWithHttpInfo() : ApiResponse<ConfigSpamquarReadSpamquarSectionResponse?> {
        val localVariableConfig = configSpamquarReadSpamquarSectionRequestConfig()

        return request<Unit, ConfigSpamquarReadSpamquarSectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configSpamquarReadSpamquarSection
     *
     * @return RequestConfig
     */
    fun configSpamquarReadSpamquarSectionRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/spamquar",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/spamquar
     * Update spamquar configuration properties
     * Update spamquar configuration properties.
     * @param configSpamquarUpdateSpamquarSectionRequest  (optional)
     * @return ConfigSpamquarUpdateSpamquarSectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configSpamquarUpdateSpamquarSection(configSpamquarUpdateSpamquarSectionRequest: ConfigSpamquarUpdateSpamquarSectionRequest? = null) : ConfigSpamquarUpdateSpamquarSectionResponse {
        val localVarResponse = configSpamquarUpdateSpamquarSectionWithHttpInfo(configSpamquarUpdateSpamquarSectionRequest = configSpamquarUpdateSpamquarSectionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigSpamquarUpdateSpamquarSectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/spamquar
     * Update spamquar configuration properties
     * Update spamquar configuration properties.
     * @param configSpamquarUpdateSpamquarSectionRequest  (optional)
     * @return ApiResponse<ConfigSpamquarUpdateSpamquarSectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configSpamquarUpdateSpamquarSectionWithHttpInfo(configSpamquarUpdateSpamquarSectionRequest: ConfigSpamquarUpdateSpamquarSectionRequest?) : ApiResponse<ConfigSpamquarUpdateSpamquarSectionResponse?> {
        val localVariableConfig = configSpamquarUpdateSpamquarSectionRequestConfig(configSpamquarUpdateSpamquarSectionRequest = configSpamquarUpdateSpamquarSectionRequest)

        return request<ConfigSpamquarUpdateSpamquarSectionRequest, ConfigSpamquarUpdateSpamquarSectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configSpamquarUpdateSpamquarSection
     *
     * @param configSpamquarUpdateSpamquarSectionRequest  (optional)
     * @return RequestConfig
     */
    fun configSpamquarUpdateSpamquarSectionRequestConfig(configSpamquarUpdateSpamquarSectionRequest: ConfigSpamquarUpdateSpamquarSectionRequest?) : RequestConfig<ConfigSpamquarUpdateSpamquarSectionRequest> {
        val localVariableBody = configSpamquarUpdateSpamquarSectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/spamquar",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
