/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.ConfigFetchmailCreateFetchmailRequest
import com.clientapi.pmg.models.ConfigFetchmailCreateFetchmailResponse
import com.clientapi.pmg.models.ConfigFetchmailDeleteFetchmailResponse
import com.clientapi.pmg.models.ConfigFetchmailGetFetchmailResponse
import com.clientapi.pmg.models.ConfigFetchmailReadGetFetchmailResponse
import com.clientapi.pmg.models.ConfigFetchmailWriteRequest
import com.clientapi.pmg.models.ConfigFetchmailWriteResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class ConfigFetchmailApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /config/fetchmail
     * Create fetchmail user configuration
     * Create fetchmail user configuration.
     * @param configFetchmailCreateFetchmailRequest 
     * @return ConfigFetchmailCreateFetchmailResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configFetchmailCreateFetchmail(configFetchmailCreateFetchmailRequest: ConfigFetchmailCreateFetchmailRequest) : ConfigFetchmailCreateFetchmailResponse {
        val localVarResponse = configFetchmailCreateFetchmailWithHttpInfo(configFetchmailCreateFetchmailRequest = configFetchmailCreateFetchmailRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigFetchmailCreateFetchmailResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/fetchmail
     * Create fetchmail user configuration
     * Create fetchmail user configuration.
     * @param configFetchmailCreateFetchmailRequest 
     * @return ApiResponse<ConfigFetchmailCreateFetchmailResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configFetchmailCreateFetchmailWithHttpInfo(configFetchmailCreateFetchmailRequest: ConfigFetchmailCreateFetchmailRequest) : ApiResponse<ConfigFetchmailCreateFetchmailResponse?> {
        val localVariableConfig = configFetchmailCreateFetchmailRequestConfig(configFetchmailCreateFetchmailRequest = configFetchmailCreateFetchmailRequest)

        return request<ConfigFetchmailCreateFetchmailRequest, ConfigFetchmailCreateFetchmailResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configFetchmailCreateFetchmail
     *
     * @param configFetchmailCreateFetchmailRequest 
     * @return RequestConfig
     */
    fun configFetchmailCreateFetchmailRequestConfig(configFetchmailCreateFetchmailRequest: ConfigFetchmailCreateFetchmailRequest) : RequestConfig<ConfigFetchmailCreateFetchmailRequest> {
        val localVariableBody = configFetchmailCreateFetchmailRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/fetchmail",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/fetchmail/{id}
     * Delete a fetchmail configuration entry
     * Delete a fetchmail configuration entry.
     * @param id Unique ID
     * @return ConfigFetchmailDeleteFetchmailResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configFetchmailDeleteFetchmail(id: kotlin.String) : ConfigFetchmailDeleteFetchmailResponse {
        val localVarResponse = configFetchmailDeleteFetchmailWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigFetchmailDeleteFetchmailResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/fetchmail/{id}
     * Delete a fetchmail configuration entry
     * Delete a fetchmail configuration entry.
     * @param id Unique ID
     * @return ApiResponse<ConfigFetchmailDeleteFetchmailResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configFetchmailDeleteFetchmailWithHttpInfo(id: kotlin.String) : ApiResponse<ConfigFetchmailDeleteFetchmailResponse?> {
        val localVariableConfig = configFetchmailDeleteFetchmailRequestConfig(id = id)

        return request<Unit, ConfigFetchmailDeleteFetchmailResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configFetchmailDeleteFetchmail
     *
     * @param id Unique ID
     * @return RequestConfig
     */
    fun configFetchmailDeleteFetchmailRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/fetchmail/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/fetchmail
     * List fetchmail users
     * List fetchmail users.
     * @return ConfigFetchmailGetFetchmailResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configFetchmailGetFetchmail() : ConfigFetchmailGetFetchmailResponse {
        val localVarResponse = configFetchmailGetFetchmailWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigFetchmailGetFetchmailResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/fetchmail
     * List fetchmail users
     * List fetchmail users.
     * @return ApiResponse<ConfigFetchmailGetFetchmailResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configFetchmailGetFetchmailWithHttpInfo() : ApiResponse<ConfigFetchmailGetFetchmailResponse?> {
        val localVariableConfig = configFetchmailGetFetchmailRequestConfig()

        return request<Unit, ConfigFetchmailGetFetchmailResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configFetchmailGetFetchmail
     *
     * @return RequestConfig
     */
    fun configFetchmailGetFetchmailRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/fetchmail",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/fetchmail/{id}
     * Read fetchmail user configuration
     * Read fetchmail user configuration.
     * @param id Unique ID
     * @return ConfigFetchmailReadGetFetchmailResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configFetchmailReadGetFetchmail(id: kotlin.String) : ConfigFetchmailReadGetFetchmailResponse {
        val localVarResponse = configFetchmailReadGetFetchmailWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigFetchmailReadGetFetchmailResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/fetchmail/{id}
     * Read fetchmail user configuration
     * Read fetchmail user configuration.
     * @param id Unique ID
     * @return ApiResponse<ConfigFetchmailReadGetFetchmailResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configFetchmailReadGetFetchmailWithHttpInfo(id: kotlin.String) : ApiResponse<ConfigFetchmailReadGetFetchmailResponse?> {
        val localVariableConfig = configFetchmailReadGetFetchmailRequestConfig(id = id)

        return request<Unit, ConfigFetchmailReadGetFetchmailResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configFetchmailReadGetFetchmail
     *
     * @param id Unique ID
     * @return RequestConfig
     */
    fun configFetchmailReadGetFetchmailRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/fetchmail/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/fetchmail/{id}
     * Update fetchmail user configuration
     * Update fetchmail user configuration.
     * @param id Unique ID
     * @param configFetchmailWriteRequest  (optional)
     * @return ConfigFetchmailWriteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configFetchmailWrite(id: kotlin.String, configFetchmailWriteRequest: ConfigFetchmailWriteRequest? = null) : ConfigFetchmailWriteResponse {
        val localVarResponse = configFetchmailWriteWithHttpInfo(id = id, configFetchmailWriteRequest = configFetchmailWriteRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigFetchmailWriteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/fetchmail/{id}
     * Update fetchmail user configuration
     * Update fetchmail user configuration.
     * @param id Unique ID
     * @param configFetchmailWriteRequest  (optional)
     * @return ApiResponse<ConfigFetchmailWriteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configFetchmailWriteWithHttpInfo(id: kotlin.String, configFetchmailWriteRequest: ConfigFetchmailWriteRequest?) : ApiResponse<ConfigFetchmailWriteResponse?> {
        val localVariableConfig = configFetchmailWriteRequestConfig(id = id, configFetchmailWriteRequest = configFetchmailWriteRequest)

        return request<ConfigFetchmailWriteRequest, ConfigFetchmailWriteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configFetchmailWrite
     *
     * @param id Unique ID
     * @param configFetchmailWriteRequest  (optional)
     * @return RequestConfig
     */
    fun configFetchmailWriteRequestConfig(id: kotlin.String, configFetchmailWriteRequest: ConfigFetchmailWriteRequest?) : RequestConfig<ConfigFetchmailWriteRequest> {
        val localVariableBody = configFetchmailWriteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/fetchmail/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
