/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.ConfigVirusquarReadVirusquarSectionResponse
import com.clientapi.pmg.models.ConfigVirusquarUpdateVirusquarSectionRequest
import com.clientapi.pmg.models.ConfigVirusquarUpdateVirusquarSectionResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class ConfigVirusquarApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /config/virusquar
     * Read virusquar configuration properties
     * Read virusquar configuration properties.
     * @return ConfigVirusquarReadVirusquarSectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configVirusquarReadVirusquarSection() : ConfigVirusquarReadVirusquarSectionResponse {
        val localVarResponse = configVirusquarReadVirusquarSectionWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigVirusquarReadVirusquarSectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/virusquar
     * Read virusquar configuration properties
     * Read virusquar configuration properties.
     * @return ApiResponse<ConfigVirusquarReadVirusquarSectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configVirusquarReadVirusquarSectionWithHttpInfo() : ApiResponse<ConfigVirusquarReadVirusquarSectionResponse?> {
        val localVariableConfig = configVirusquarReadVirusquarSectionRequestConfig()

        return request<Unit, ConfigVirusquarReadVirusquarSectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configVirusquarReadVirusquarSection
     *
     * @return RequestConfig
     */
    fun configVirusquarReadVirusquarSectionRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/virusquar",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/virusquar
     * Update virusquar configuration properties
     * Update virusquar configuration properties.
     * @param configVirusquarUpdateVirusquarSectionRequest  (optional)
     * @return ConfigVirusquarUpdateVirusquarSectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configVirusquarUpdateVirusquarSection(configVirusquarUpdateVirusquarSectionRequest: ConfigVirusquarUpdateVirusquarSectionRequest? = null) : ConfigVirusquarUpdateVirusquarSectionResponse {
        val localVarResponse = configVirusquarUpdateVirusquarSectionWithHttpInfo(configVirusquarUpdateVirusquarSectionRequest = configVirusquarUpdateVirusquarSectionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigVirusquarUpdateVirusquarSectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/virusquar
     * Update virusquar configuration properties
     * Update virusquar configuration properties.
     * @param configVirusquarUpdateVirusquarSectionRequest  (optional)
     * @return ApiResponse<ConfigVirusquarUpdateVirusquarSectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configVirusquarUpdateVirusquarSectionWithHttpInfo(configVirusquarUpdateVirusquarSectionRequest: ConfigVirusquarUpdateVirusquarSectionRequest?) : ApiResponse<ConfigVirusquarUpdateVirusquarSectionResponse?> {
        val localVariableConfig = configVirusquarUpdateVirusquarSectionRequestConfig(configVirusquarUpdateVirusquarSectionRequest = configVirusquarUpdateVirusquarSectionRequest)

        return request<ConfigVirusquarUpdateVirusquarSectionRequest, ConfigVirusquarUpdateVirusquarSectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configVirusquarUpdateVirusquarSection
     *
     * @param configVirusquarUpdateVirusquarSectionRequest  (optional)
     * @return RequestConfig
     */
    fun configVirusquarUpdateVirusquarSectionRequestConfig(configVirusquarUpdateVirusquarSectionRequest: ConfigVirusquarUpdateVirusquarSectionRequest?) : RequestConfig<ConfigVirusquarUpdateVirusquarSectionRequest> {
        val localVariableBody = configVirusquarUpdateVirusquarSectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/virusquar",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
