/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.NodesTimeSetTimezoneRequest
import com.clientapi.pmg.models.NodesTimeSetTimezoneResponse
import com.clientapi.pmg.models.NodesTimeTimeResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class NodesTimeApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * PUT /nodes/{node}/time
     * Set time zone
     * Set time zone.
     * @param node The cluster node name.
     * @param nodesTimeSetTimezoneRequest 
     * @return NodesTimeSetTimezoneResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesTimeSetTimezone(node: kotlin.String, nodesTimeSetTimezoneRequest: NodesTimeSetTimezoneRequest) : NodesTimeSetTimezoneResponse {
        val localVarResponse = nodesTimeSetTimezoneWithHttpInfo(node = node, nodesTimeSetTimezoneRequest = nodesTimeSetTimezoneRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesTimeSetTimezoneResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/time
     * Set time zone
     * Set time zone.
     * @param node The cluster node name.
     * @param nodesTimeSetTimezoneRequest 
     * @return ApiResponse<NodesTimeSetTimezoneResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesTimeSetTimezoneWithHttpInfo(node: kotlin.String, nodesTimeSetTimezoneRequest: NodesTimeSetTimezoneRequest) : ApiResponse<NodesTimeSetTimezoneResponse?> {
        val localVariableConfig = nodesTimeSetTimezoneRequestConfig(node = node, nodesTimeSetTimezoneRequest = nodesTimeSetTimezoneRequest)

        return request<NodesTimeSetTimezoneRequest, NodesTimeSetTimezoneResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesTimeSetTimezone
     *
     * @param node The cluster node name.
     * @param nodesTimeSetTimezoneRequest 
     * @return RequestConfig
     */
    fun nodesTimeSetTimezoneRequestConfig(node: kotlin.String, nodesTimeSetTimezoneRequest: NodesTimeSetTimezoneRequest) : RequestConfig<NodesTimeSetTimezoneRequest> {
        val localVariableBody = nodesTimeSetTimezoneRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/time".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/time
     * Read server time and time zone settings
     * Read server time and time zone settings.
     * @param node The cluster node name.
     * @return NodesTimeTimeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesTimeTime(node: kotlin.String) : NodesTimeTimeResponse {
        val localVarResponse = nodesTimeTimeWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesTimeTimeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/time
     * Read server time and time zone settings
     * Read server time and time zone settings.
     * @param node The cluster node name.
     * @return ApiResponse<NodesTimeTimeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesTimeTimeWithHttpInfo(node: kotlin.String) : ApiResponse<NodesTimeTimeResponse?> {
        val localVariableConfig = nodesTimeTimeRequestConfig(node = node)

        return request<Unit, NodesTimeTimeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesTimeTime
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesTimeTimeRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/time".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
