/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.NodesCertificatesAcmeCertIndexResponse
import com.clientapi.pmg.models.NodesCertificatesCustomCertIndexResponse
import com.clientapi.pmg.models.NodesCertificatesGetCertificatesResponse
import com.clientapi.pmg.models.NodesCertificatesInfoResponse
import com.clientapi.pmg.models.NodesCertificatesNewAcmeCertRequest
import com.clientapi.pmg.models.NodesCertificatesNewAcmeCertResponse
import com.clientapi.pmg.models.NodesCertificatesRemoveCustomCertResponse
import com.clientapi.pmg.models.NodesCertificatesRenewAcmeCertRequest
import com.clientapi.pmg.models.NodesCertificatesRenewAcmeCertResponse
import com.clientapi.pmg.models.NodesCertificatesRevokeAcmeCertResponse
import com.clientapi.pmg.models.NodesCertificatesUploadCustomCertRequest
import com.clientapi.pmg.models.NodesCertificatesUploadCustomCertResponse
import com.clientapi.pmg.models.PmgBoolean
import com.clientapi.pmg.models.PmgError
import com.clientapi.pmg.models.PmgNodesCertificatesTypeEnum

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class NodesCertificatesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /nodes/{node}/certificates/acme
     * ACME Certificate index
     * ACME Certificate index.
     * @param node The cluster node name.
     * @return NodesCertificatesAcmeCertIndexResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesAcmeCertIndex(node: kotlin.String) : NodesCertificatesAcmeCertIndexResponse {
        val localVarResponse = nodesCertificatesAcmeCertIndexWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesAcmeCertIndexResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/certificates/acme
     * ACME Certificate index
     * ACME Certificate index.
     * @param node The cluster node name.
     * @return ApiResponse<NodesCertificatesAcmeCertIndexResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesAcmeCertIndexWithHttpInfo(node: kotlin.String) : ApiResponse<NodesCertificatesAcmeCertIndexResponse?> {
        val localVariableConfig = nodesCertificatesAcmeCertIndexRequestConfig(node = node)

        return request<Unit, NodesCertificatesAcmeCertIndexResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesAcmeCertIndex
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesCertificatesAcmeCertIndexRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/certificates/acme".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/certificates/custom
     * Certificate index
     * Certificate index.
     * @param node The cluster node name.
     * @return NodesCertificatesCustomCertIndexResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesCustomCertIndex(node: kotlin.String) : NodesCertificatesCustomCertIndexResponse {
        val localVarResponse = nodesCertificatesCustomCertIndexWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesCustomCertIndexResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/certificates/custom
     * Certificate index
     * Certificate index.
     * @param node The cluster node name.
     * @return ApiResponse<NodesCertificatesCustomCertIndexResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesCustomCertIndexWithHttpInfo(node: kotlin.String) : ApiResponse<NodesCertificatesCustomCertIndexResponse?> {
        val localVariableConfig = nodesCertificatesCustomCertIndexRequestConfig(node = node)

        return request<Unit, NodesCertificatesCustomCertIndexResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesCustomCertIndex
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesCertificatesCustomCertIndexRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/certificates/custom".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/certificates
     * Node index
     * Node index.
     * @param node The cluster node name.
     * @return NodesCertificatesGetCertificatesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesGetCertificates(node: kotlin.String) : NodesCertificatesGetCertificatesResponse {
        val localVarResponse = nodesCertificatesGetCertificatesWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesGetCertificatesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/certificates
     * Node index
     * Node index.
     * @param node The cluster node name.
     * @return ApiResponse<NodesCertificatesGetCertificatesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesGetCertificatesWithHttpInfo(node: kotlin.String) : ApiResponse<NodesCertificatesGetCertificatesResponse?> {
        val localVariableConfig = nodesCertificatesGetCertificatesRequestConfig(node = node)

        return request<Unit, NodesCertificatesGetCertificatesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesGetCertificates
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesCertificatesGetCertificatesRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/certificates".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/certificates/info
     * Get information about the node&#39;s certificates
     * Get information about the node&#39;s certificates.
     * @param node The cluster node name.
     * @return NodesCertificatesInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesInfo(node: kotlin.String) : NodesCertificatesInfoResponse {
        val localVarResponse = nodesCertificatesInfoWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/certificates/info
     * Get information about the node&#39;s certificates
     * Get information about the node&#39;s certificates.
     * @param node The cluster node name.
     * @return ApiResponse<NodesCertificatesInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesInfoWithHttpInfo(node: kotlin.String) : ApiResponse<NodesCertificatesInfoResponse?> {
        val localVariableConfig = nodesCertificatesInfoRequestConfig(node = node)

        return request<Unit, NodesCertificatesInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesInfo
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesCertificatesInfoRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/certificates/info".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/certificates/acme/{type}
     * Order a new certificate from ACME-compatible CA
     * Order a new certificate from ACME-compatible CA.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesNewAcmeCertRequest  (optional)
     * @return NodesCertificatesNewAcmeCertResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesNewAcmeCert(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesNewAcmeCertRequest: NodesCertificatesNewAcmeCertRequest? = null) : NodesCertificatesNewAcmeCertResponse {
        val localVarResponse = nodesCertificatesNewAcmeCertWithHttpInfo(node = node, type = type, nodesCertificatesNewAcmeCertRequest = nodesCertificatesNewAcmeCertRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesNewAcmeCertResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/certificates/acme/{type}
     * Order a new certificate from ACME-compatible CA
     * Order a new certificate from ACME-compatible CA.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesNewAcmeCertRequest  (optional)
     * @return ApiResponse<NodesCertificatesNewAcmeCertResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesNewAcmeCertWithHttpInfo(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesNewAcmeCertRequest: NodesCertificatesNewAcmeCertRequest?) : ApiResponse<NodesCertificatesNewAcmeCertResponse?> {
        val localVariableConfig = nodesCertificatesNewAcmeCertRequestConfig(node = node, type = type, nodesCertificatesNewAcmeCertRequest = nodesCertificatesNewAcmeCertRequest)

        return request<NodesCertificatesNewAcmeCertRequest, NodesCertificatesNewAcmeCertResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesNewAcmeCert
     *
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesNewAcmeCertRequest  (optional)
     * @return RequestConfig
     */
    fun nodesCertificatesNewAcmeCertRequestConfig(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesNewAcmeCertRequest: NodesCertificatesNewAcmeCertRequest?) : RequestConfig<NodesCertificatesNewAcmeCertRequest> {
        val localVariableBody = nodesCertificatesNewAcmeCertRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/certificates/acme/{type}".replace("{"+"node"+"}", encodeURIComponent(node.toString())).replace("{"+"type"+"}", encodeURIComponent(type.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/certificates/custom/{type}
     * DELETE custom certificate chain and key
     * DELETE custom certificate chain and key.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param restart Restart pmgproxy. (optional)
     * @return NodesCertificatesRemoveCustomCertResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesRemoveCustomCert(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, restart: PmgBoolean? = null) : NodesCertificatesRemoveCustomCertResponse {
        val localVarResponse = nodesCertificatesRemoveCustomCertWithHttpInfo(node = node, type = type, restart = restart)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesRemoveCustomCertResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/certificates/custom/{type}
     * DELETE custom certificate chain and key
     * DELETE custom certificate chain and key.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param restart Restart pmgproxy. (optional)
     * @return ApiResponse<NodesCertificatesRemoveCustomCertResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesRemoveCustomCertWithHttpInfo(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, restart: PmgBoolean?) : ApiResponse<NodesCertificatesRemoveCustomCertResponse?> {
        val localVariableConfig = nodesCertificatesRemoveCustomCertRequestConfig(node = node, type = type, restart = restart)

        return request<Unit, NodesCertificatesRemoveCustomCertResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesRemoveCustomCert
     *
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param restart Restart pmgproxy. (optional)
     * @return RequestConfig
     */
    fun nodesCertificatesRemoveCustomCertRequestConfig(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, restart: PmgBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (restart != null) {
                    put("restart", listOf(restart.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/certificates/custom/{type}".replace("{"+"node"+"}", encodeURIComponent(node.toString())).replace("{"+"type"+"}", encodeURIComponent(type.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/certificates/acme/{type}
     * Renew existing certificate from CA
     * Renew existing certificate from CA.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesRenewAcmeCertRequest  (optional)
     * @return NodesCertificatesRenewAcmeCertResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesRenewAcmeCert(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesRenewAcmeCertRequest: NodesCertificatesRenewAcmeCertRequest? = null) : NodesCertificatesRenewAcmeCertResponse {
        val localVarResponse = nodesCertificatesRenewAcmeCertWithHttpInfo(node = node, type = type, nodesCertificatesRenewAcmeCertRequest = nodesCertificatesRenewAcmeCertRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesRenewAcmeCertResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/certificates/acme/{type}
     * Renew existing certificate from CA
     * Renew existing certificate from CA.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesRenewAcmeCertRequest  (optional)
     * @return ApiResponse<NodesCertificatesRenewAcmeCertResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesRenewAcmeCertWithHttpInfo(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesRenewAcmeCertRequest: NodesCertificatesRenewAcmeCertRequest?) : ApiResponse<NodesCertificatesRenewAcmeCertResponse?> {
        val localVariableConfig = nodesCertificatesRenewAcmeCertRequestConfig(node = node, type = type, nodesCertificatesRenewAcmeCertRequest = nodesCertificatesRenewAcmeCertRequest)

        return request<NodesCertificatesRenewAcmeCertRequest, NodesCertificatesRenewAcmeCertResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesRenewAcmeCert
     *
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesRenewAcmeCertRequest  (optional)
     * @return RequestConfig
     */
    fun nodesCertificatesRenewAcmeCertRequestConfig(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesRenewAcmeCertRequest: NodesCertificatesRenewAcmeCertRequest?) : RequestConfig<NodesCertificatesRenewAcmeCertRequest> {
        val localVariableBody = nodesCertificatesRenewAcmeCertRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/certificates/acme/{type}".replace("{"+"node"+"}", encodeURIComponent(node.toString())).replace("{"+"type"+"}", encodeURIComponent(type.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/certificates/acme/{type}
     * Revoke existing certificate from CA
     * Revoke existing certificate from CA.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @return NodesCertificatesRevokeAcmeCertResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesRevokeAcmeCert(node: kotlin.String, type: PmgNodesCertificatesTypeEnum) : NodesCertificatesRevokeAcmeCertResponse {
        val localVarResponse = nodesCertificatesRevokeAcmeCertWithHttpInfo(node = node, type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesRevokeAcmeCertResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/certificates/acme/{type}
     * Revoke existing certificate from CA
     * Revoke existing certificate from CA.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @return ApiResponse<NodesCertificatesRevokeAcmeCertResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesRevokeAcmeCertWithHttpInfo(node: kotlin.String, type: PmgNodesCertificatesTypeEnum) : ApiResponse<NodesCertificatesRevokeAcmeCertResponse?> {
        val localVariableConfig = nodesCertificatesRevokeAcmeCertRequestConfig(node = node, type = type)

        return request<Unit, NodesCertificatesRevokeAcmeCertResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesRevokeAcmeCert
     *
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @return RequestConfig
     */
    fun nodesCertificatesRevokeAcmeCertRequestConfig(node: kotlin.String, type: PmgNodesCertificatesTypeEnum) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/certificates/acme/{type}".replace("{"+"node"+"}", encodeURIComponent(node.toString())).replace("{"+"type"+"}", encodeURIComponent(type.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/certificates/custom/{type}
     * Upload or update custom certificate chain and key
     * Upload or update custom certificate chain and key.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesUploadCustomCertRequest 
     * @return NodesCertificatesUploadCustomCertResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCertificatesUploadCustomCert(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesUploadCustomCertRequest: NodesCertificatesUploadCustomCertRequest) : NodesCertificatesUploadCustomCertResponse {
        val localVarResponse = nodesCertificatesUploadCustomCertWithHttpInfo(node = node, type = type, nodesCertificatesUploadCustomCertRequest = nodesCertificatesUploadCustomCertRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCertificatesUploadCustomCertResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/certificates/custom/{type}
     * Upload or update custom certificate chain and key
     * Upload or update custom certificate chain and key.
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesUploadCustomCertRequest 
     * @return ApiResponse<NodesCertificatesUploadCustomCertResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCertificatesUploadCustomCertWithHttpInfo(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesUploadCustomCertRequest: NodesCertificatesUploadCustomCertRequest) : ApiResponse<NodesCertificatesUploadCustomCertResponse?> {
        val localVariableConfig = nodesCertificatesUploadCustomCertRequestConfig(node = node, type = type, nodesCertificatesUploadCustomCertRequest = nodesCertificatesUploadCustomCertRequest)

        return request<NodesCertificatesUploadCustomCertRequest, NodesCertificatesUploadCustomCertResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCertificatesUploadCustomCert
     *
     * @param node The cluster node name.
     * @param type The TLS certificate type (API or SMTP certificate).
     * @param nodesCertificatesUploadCustomCertRequest 
     * @return RequestConfig
     */
    fun nodesCertificatesUploadCustomCertRequestConfig(node: kotlin.String, type: PmgNodesCertificatesTypeEnum, nodesCertificatesUploadCustomCertRequest: NodesCertificatesUploadCustomCertRequest) : RequestConfig<NodesCertificatesUploadCustomCertRequest> {
        val localVariableBody = nodesCertificatesUploadCustomCertRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/certificates/custom/{type}".replace("{"+"node"+"}", encodeURIComponent(node.toString())).replace("{"+"type"+"}", encodeURIComponent(type.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
