/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.NodesTrackerListMailsResponse
import com.clientapi.pmg.models.NodesTrackerMaillogResponse
import com.clientapi.pmg.models.PmgBoolean
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class NodesTrackerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /nodes/{node}/tracker
     * Read mail list
     * Read mail list.
     * @param node The cluster node name.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param from Sender email address filter. (optional)
     * @param greylist Include Greylisted entries. (optional)
     * @param ndr Include NDRs (non delivery reports). (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @param target Receiver email address filter. (optional)
     * @param xfilter Only include mails containing this filter string. (optional)
     * @return NodesTrackerListMailsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesTrackerListMails(node: kotlin.String, endtime: kotlin.Long? = null, from: kotlin.String? = null, greylist: PmgBoolean? = null, ndr: PmgBoolean? = null, starttime: kotlin.Long? = null, target: kotlin.String? = null, xfilter: kotlin.String? = null) : NodesTrackerListMailsResponse {
        val localVarResponse = nodesTrackerListMailsWithHttpInfo(node = node, endtime = endtime, from = from, greylist = greylist, ndr = ndr, starttime = starttime, target = target, xfilter = xfilter)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesTrackerListMailsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/tracker
     * Read mail list
     * Read mail list.
     * @param node The cluster node name.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param from Sender email address filter. (optional)
     * @param greylist Include Greylisted entries. (optional)
     * @param ndr Include NDRs (non delivery reports). (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @param target Receiver email address filter. (optional)
     * @param xfilter Only include mails containing this filter string. (optional)
     * @return ApiResponse<NodesTrackerListMailsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesTrackerListMailsWithHttpInfo(node: kotlin.String, endtime: kotlin.Long?, from: kotlin.String?, greylist: PmgBoolean?, ndr: PmgBoolean?, starttime: kotlin.Long?, target: kotlin.String?, xfilter: kotlin.String?) : ApiResponse<NodesTrackerListMailsResponse?> {
        val localVariableConfig = nodesTrackerListMailsRequestConfig(node = node, endtime = endtime, from = from, greylist = greylist, ndr = ndr, starttime = starttime, target = target, xfilter = xfilter)

        return request<Unit, NodesTrackerListMailsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesTrackerListMails
     *
     * @param node The cluster node name.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param from Sender email address filter. (optional)
     * @param greylist Include Greylisted entries. (optional)
     * @param ndr Include NDRs (non delivery reports). (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @param target Receiver email address filter. (optional)
     * @param xfilter Only include mails containing this filter string. (optional)
     * @return RequestConfig
     */
    fun nodesTrackerListMailsRequestConfig(node: kotlin.String, endtime: kotlin.Long?, from: kotlin.String?, greylist: PmgBoolean?, ndr: PmgBoolean?, starttime: kotlin.Long?, target: kotlin.String?, xfilter: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endtime != null) {
                    put("endtime", listOf(endtime.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (greylist != null) {
                    put("greylist", listOf(greylist.toString()))
                }
                if (ndr != null) {
                    put("ndr", listOf(ndr.toString()))
                }
                if (starttime != null) {
                    put("starttime", listOf(starttime.toString()))
                }
                if (target != null) {
                    put("target", listOf(target.toString()))
                }
                if (xfilter != null) {
                    put("xfilter", listOf(xfilter.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/tracker".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/tracker/{id}
     * Get the detailed syslog entries for a specific mail ID
     * Get the detailed syslog entries for a specific mail ID.
     * @param id Mail ID (as returned by the list API).
     * @param node The cluster node name.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return NodesTrackerMaillogResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesTrackerMaillog(id: kotlin.String, node: kotlin.String, endtime: kotlin.Long? = null, starttime: kotlin.Long? = null) : NodesTrackerMaillogResponse {
        val localVarResponse = nodesTrackerMaillogWithHttpInfo(id = id, node = node, endtime = endtime, starttime = starttime)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesTrackerMaillogResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/tracker/{id}
     * Get the detailed syslog entries for a specific mail ID
     * Get the detailed syslog entries for a specific mail ID.
     * @param id Mail ID (as returned by the list API).
     * @param node The cluster node name.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return ApiResponse<NodesTrackerMaillogResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesTrackerMaillogWithHttpInfo(id: kotlin.String, node: kotlin.String, endtime: kotlin.Long?, starttime: kotlin.Long?) : ApiResponse<NodesTrackerMaillogResponse?> {
        val localVariableConfig = nodesTrackerMaillogRequestConfig(id = id, node = node, endtime = endtime, starttime = starttime)

        return request<Unit, NodesTrackerMaillogResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesTrackerMaillog
     *
     * @param id Mail ID (as returned by the list API).
     * @param node The cluster node name.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return RequestConfig
     */
    fun nodesTrackerMaillogRequestConfig(id: kotlin.String, node: kotlin.String, endtime: kotlin.Long?, starttime: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endtime != null) {
                    put("endtime", listOf(endtime.toString()))
                }
                if (starttime != null) {
                    put("starttime", listOf(starttime.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/tracker/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
