/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.NodesBackupBackupRequest
import com.clientapi.pmg.models.NodesBackupBackupResponse
import com.clientapi.pmg.models.NodesBackupDeleteBackupResponse
import com.clientapi.pmg.models.NodesBackupDownloadResponse
import com.clientapi.pmg.models.NodesBackupGetBackupResponse
import com.clientapi.pmg.models.NodesBackupRestoreRequest
import com.clientapi.pmg.models.NodesBackupRestoreResponse
import com.clientapi.pmg.models.PmgError

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class NodesBackupApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/backup
     * Backup the system configuration
     * Backup the system configuration.
     * @param node The cluster node name.
     * @param nodesBackupBackupRequest  (optional)
     * @return NodesBackupBackupResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesBackupBackup(node: kotlin.String, nodesBackupBackupRequest: NodesBackupBackupRequest? = null) : NodesBackupBackupResponse {
        val localVarResponse = nodesBackupBackupWithHttpInfo(node = node, nodesBackupBackupRequest = nodesBackupBackupRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesBackupBackupResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/backup
     * Backup the system configuration
     * Backup the system configuration.
     * @param node The cluster node name.
     * @param nodesBackupBackupRequest  (optional)
     * @return ApiResponse<NodesBackupBackupResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesBackupBackupWithHttpInfo(node: kotlin.String, nodesBackupBackupRequest: NodesBackupBackupRequest?) : ApiResponse<NodesBackupBackupResponse?> {
        val localVariableConfig = nodesBackupBackupRequestConfig(node = node, nodesBackupBackupRequest = nodesBackupBackupRequest)

        return request<NodesBackupBackupRequest, NodesBackupBackupResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesBackupBackup
     *
     * @param node The cluster node name.
     * @param nodesBackupBackupRequest  (optional)
     * @return RequestConfig
     */
    fun nodesBackupBackupRequestConfig(node: kotlin.String, nodesBackupBackupRequest: NodesBackupBackupRequest?) : RequestConfig<NodesBackupBackupRequest> {
        val localVariableBody = nodesBackupBackupRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/backup".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/backup/{filename}
     * Delete a backup file
     * Delete a backup file.
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @return NodesBackupDeleteBackupResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesBackupDeleteBackup(filename: kotlin.String, node: kotlin.String) : NodesBackupDeleteBackupResponse {
        val localVarResponse = nodesBackupDeleteBackupWithHttpInfo(filename = filename, node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesBackupDeleteBackupResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/backup/{filename}
     * Delete a backup file
     * Delete a backup file.
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @return ApiResponse<NodesBackupDeleteBackupResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesBackupDeleteBackupWithHttpInfo(filename: kotlin.String, node: kotlin.String) : ApiResponse<NodesBackupDeleteBackupResponse?> {
        val localVariableConfig = nodesBackupDeleteBackupRequestConfig(filename = filename, node = node)

        return request<Unit, NodesBackupDeleteBackupResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesBackupDeleteBackup
     *
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesBackupDeleteBackupRequestConfig(filename: kotlin.String, node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/backup/{filename}".replace("{"+"filename"+"}", encodeURIComponent(filename.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/backup/{filename}
     * Download a backup file
     * Download a backup file.
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @return NodesBackupDownloadResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesBackupDownload(filename: kotlin.String, node: kotlin.String) : NodesBackupDownloadResponse {
        val localVarResponse = nodesBackupDownloadWithHttpInfo(filename = filename, node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesBackupDownloadResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/backup/{filename}
     * Download a backup file
     * Download a backup file.
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @return ApiResponse<NodesBackupDownloadResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesBackupDownloadWithHttpInfo(filename: kotlin.String, node: kotlin.String) : ApiResponse<NodesBackupDownloadResponse?> {
        val localVariableConfig = nodesBackupDownloadRequestConfig(filename = filename, node = node)

        return request<Unit, NodesBackupDownloadResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesBackupDownload
     *
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesBackupDownloadRequestConfig(filename: kotlin.String, node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/backup/{filename}".replace("{"+"filename"+"}", encodeURIComponent(filename.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/backup
     * List all stored backups (files named proxmox-backup_{DATE}
     * List all stored backups (files named proxmox-backup_{DATE}.tgz).
     * @param node The cluster node name.
     * @return NodesBackupGetBackupResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesBackupGetBackup(node: kotlin.String) : NodesBackupGetBackupResponse {
        val localVarResponse = nodesBackupGetBackupWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesBackupGetBackupResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/backup
     * List all stored backups (files named proxmox-backup_{DATE}
     * List all stored backups (files named proxmox-backup_{DATE}.tgz).
     * @param node The cluster node name.
     * @return ApiResponse<NodesBackupGetBackupResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesBackupGetBackupWithHttpInfo(node: kotlin.String) : ApiResponse<NodesBackupGetBackupResponse?> {
        val localVariableConfig = nodesBackupGetBackupRequestConfig(node = node)

        return request<Unit, NodesBackupGetBackupResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesBackupGetBackup
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesBackupGetBackupRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/backup".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/backup/{filename}
     * Restore the system configuration
     * Restore the system configuration.
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @param nodesBackupRestoreRequest  (optional)
     * @return NodesBackupRestoreResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesBackupRestore(filename: kotlin.String, node: kotlin.String, nodesBackupRestoreRequest: NodesBackupRestoreRequest? = null) : NodesBackupRestoreResponse {
        val localVarResponse = nodesBackupRestoreWithHttpInfo(filename = filename, node = node, nodesBackupRestoreRequest = nodesBackupRestoreRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesBackupRestoreResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/backup/{filename}
     * Restore the system configuration
     * Restore the system configuration.
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @param nodesBackupRestoreRequest  (optional)
     * @return ApiResponse<NodesBackupRestoreResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesBackupRestoreWithHttpInfo(filename: kotlin.String, node: kotlin.String, nodesBackupRestoreRequest: NodesBackupRestoreRequest?) : ApiResponse<NodesBackupRestoreResponse?> {
        val localVariableConfig = nodesBackupRestoreRequestConfig(filename = filename, node = node, nodesBackupRestoreRequest = nodesBackupRestoreRequest)

        return request<NodesBackupRestoreRequest, NodesBackupRestoreResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesBackupRestore
     *
     * @param filename The backup file name.
     * @param node The cluster node name.
     * @param nodesBackupRestoreRequest  (optional)
     * @return RequestConfig
     */
    fun nodesBackupRestoreRequestConfig(filename: kotlin.String, node: kotlin.String, nodesBackupRestoreRequest: NodesBackupRestoreRequest?) : RequestConfig<NodesBackupRestoreRequest> {
        val localVariableBody = nodesBackupRestoreRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/backup/{filename}".replace("{"+"filename"+"}", encodeURIComponent(filename.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
