/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.PmgError
import com.clientapi.pmg.models.QuarantineBlacklistBlacklistAddRequest
import com.clientapi.pmg.models.QuarantineBlocklistBlocklistAddResponse
import com.clientapi.pmg.models.QuarantineBlocklistBlocklistDeleteBaseResponse
import com.clientapi.pmg.models.QuarantineBlocklistBlocklistResponse

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class QuarantineBlocklistApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /quarantine/blocklist
     * Show user blocklist
     * Show user blocklist.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return QuarantineBlocklistBlocklistResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineBlocklistBlocklist(pmail: kotlin.String? = null) : QuarantineBlocklistBlocklistResponse {
        val localVarResponse = quarantineBlocklistBlocklistWithHttpInfo(pmail = pmail)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineBlocklistBlocklistResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/blocklist
     * Show user blocklist
     * Show user blocklist.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return ApiResponse<QuarantineBlocklistBlocklistResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineBlocklistBlocklistWithHttpInfo(pmail: kotlin.String?) : ApiResponse<QuarantineBlocklistBlocklistResponse?> {
        val localVariableConfig = quarantineBlocklistBlocklistRequestConfig(pmail = pmail)

        return request<Unit, QuarantineBlocklistBlocklistResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineBlocklistBlocklist
     *
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return RequestConfig
     */
    fun quarantineBlocklistBlocklistRequestConfig(pmail: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/blocklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /quarantine/blocklist
     * Add user blocklist entries
     * Add user blocklist entries.
     * @param quarantineBlacklistBlacklistAddRequest 
     * @return QuarantineBlocklistBlocklistAddResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineBlocklistBlocklistAdd(quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest) : QuarantineBlocklistBlocklistAddResponse {
        val localVarResponse = quarantineBlocklistBlocklistAddWithHttpInfo(quarantineBlacklistBlacklistAddRequest = quarantineBlacklistBlacklistAddRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineBlocklistBlocklistAddResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /quarantine/blocklist
     * Add user blocklist entries
     * Add user blocklist entries.
     * @param quarantineBlacklistBlacklistAddRequest 
     * @return ApiResponse<QuarantineBlocklistBlocklistAddResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineBlocklistBlocklistAddWithHttpInfo(quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest) : ApiResponse<QuarantineBlocklistBlocklistAddResponse?> {
        val localVariableConfig = quarantineBlocklistBlocklistAddRequestConfig(quarantineBlacklistBlacklistAddRequest = quarantineBlacklistBlacklistAddRequest)

        return request<QuarantineBlacklistBlacklistAddRequest, QuarantineBlocklistBlocklistAddResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineBlocklistBlocklistAdd
     *
     * @param quarantineBlacklistBlacklistAddRequest 
     * @return RequestConfig
     */
    fun quarantineBlocklistBlocklistAddRequestConfig(quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest) : RequestConfig<QuarantineBlacklistBlacklistAddRequest> {
        val localVariableBody = quarantineBlacklistBlacklistAddRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/quarantine/blocklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /quarantine/blocklist
     * Delete user blocklist entries
     * Delete user blocklist entries.
     * @param address The address, or comma-separated list of addresses, you want to remove.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return QuarantineBlocklistBlocklistDeleteBaseResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineBlocklistBlocklistDeleteBase(address: kotlin.String, pmail: kotlin.String? = null) : QuarantineBlocklistBlocklistDeleteBaseResponse {
        val localVarResponse = quarantineBlocklistBlocklistDeleteBaseWithHttpInfo(address = address, pmail = pmail)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineBlocklistBlocklistDeleteBaseResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /quarantine/blocklist
     * Delete user blocklist entries
     * Delete user blocklist entries.
     * @param address The address, or comma-separated list of addresses, you want to remove.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return ApiResponse<QuarantineBlocklistBlocklistDeleteBaseResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineBlocklistBlocklistDeleteBaseWithHttpInfo(address: kotlin.String, pmail: kotlin.String?) : ApiResponse<QuarantineBlocklistBlocklistDeleteBaseResponse?> {
        val localVariableConfig = quarantineBlocklistBlocklistDeleteBaseRequestConfig(address = address, pmail = pmail)

        return request<Unit, QuarantineBlocklistBlocklistDeleteBaseResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineBlocklistBlocklistDeleteBase
     *
     * @param address The address, or comma-separated list of addresses, you want to remove.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return RequestConfig
     */
    fun quarantineBlocklistBlocklistDeleteBaseRequestConfig(address: kotlin.String, pmail: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("address", listOf(address.toString()))
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/quarantine/blocklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
