/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.PmgError
import com.clientapi.pmg.models.QuarantineBlacklistBlacklistAddRequest
import com.clientapi.pmg.models.QuarantineBlacklistBlacklistAddResponse
import com.clientapi.pmg.models.QuarantineBlacklistBlacklistDeleteBaseResponse
import com.clientapi.pmg.models.QuarantineBlacklistBlacklistResponse

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class QuarantineBlacklistApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /quarantine/blacklist
     * Show user blocklist
     * Show user blocklist.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return QuarantineBlacklistBlacklistResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineBlacklistBlacklist(pmail: kotlin.String? = null) : QuarantineBlacklistBlacklistResponse {
        val localVarResponse = quarantineBlacklistBlacklistWithHttpInfo(pmail = pmail)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineBlacklistBlacklistResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/blacklist
     * Show user blocklist
     * Show user blocklist.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return ApiResponse<QuarantineBlacklistBlacklistResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineBlacklistBlacklistWithHttpInfo(pmail: kotlin.String?) : ApiResponse<QuarantineBlacklistBlacklistResponse?> {
        val localVariableConfig = quarantineBlacklistBlacklistRequestConfig(pmail = pmail)

        return request<Unit, QuarantineBlacklistBlacklistResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineBlacklistBlacklist
     *
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return RequestConfig
     */
    fun quarantineBlacklistBlacklistRequestConfig(pmail: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/blacklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /quarantine/blacklist
     * Add user blocklist entries
     * Add user blocklist entries.
     * @param quarantineBlacklistBlacklistAddRequest 
     * @return QuarantineBlacklistBlacklistAddResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineBlacklistBlacklistAdd(quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest) : QuarantineBlacklistBlacklistAddResponse {
        val localVarResponse = quarantineBlacklistBlacklistAddWithHttpInfo(quarantineBlacklistBlacklistAddRequest = quarantineBlacklistBlacklistAddRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineBlacklistBlacklistAddResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /quarantine/blacklist
     * Add user blocklist entries
     * Add user blocklist entries.
     * @param quarantineBlacklistBlacklistAddRequest 
     * @return ApiResponse<QuarantineBlacklistBlacklistAddResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineBlacklistBlacklistAddWithHttpInfo(quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest) : ApiResponse<QuarantineBlacklistBlacklistAddResponse?> {
        val localVariableConfig = quarantineBlacklistBlacklistAddRequestConfig(quarantineBlacklistBlacklistAddRequest = quarantineBlacklistBlacklistAddRequest)

        return request<QuarantineBlacklistBlacklistAddRequest, QuarantineBlacklistBlacklistAddResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineBlacklistBlacklistAdd
     *
     * @param quarantineBlacklistBlacklistAddRequest 
     * @return RequestConfig
     */
    fun quarantineBlacklistBlacklistAddRequestConfig(quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest) : RequestConfig<QuarantineBlacklistBlacklistAddRequest> {
        val localVariableBody = quarantineBlacklistBlacklistAddRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/quarantine/blacklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /quarantine/blacklist
     * Delete user blocklist entries
     * Delete user blocklist entries.
     * @param address The address, or comma-separated list of addresses, you want to remove.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return QuarantineBlacklistBlacklistDeleteBaseResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineBlacklistBlacklistDeleteBase(address: kotlin.String, pmail: kotlin.String? = null) : QuarantineBlacklistBlacklistDeleteBaseResponse {
        val localVarResponse = quarantineBlacklistBlacklistDeleteBaseWithHttpInfo(address = address, pmail = pmail)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineBlacklistBlacklistDeleteBaseResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /quarantine/blacklist
     * Delete user blocklist entries
     * Delete user blocklist entries.
     * @param address The address, or comma-separated list of addresses, you want to remove.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return ApiResponse<QuarantineBlacklistBlacklistDeleteBaseResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineBlacklistBlacklistDeleteBaseWithHttpInfo(address: kotlin.String, pmail: kotlin.String?) : ApiResponse<QuarantineBlacklistBlacklistDeleteBaseResponse?> {
        val localVariableConfig = quarantineBlacklistBlacklistDeleteBaseRequestConfig(address = address, pmail = pmail)

        return request<Unit, QuarantineBlacklistBlacklistDeleteBaseResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineBlacklistBlacklistDeleteBase
     *
     * @param address The address, or comma-separated list of addresses, you want to remove.
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @return RequestConfig
     */
    fun quarantineBlacklistBlacklistDeleteBaseRequestConfig(address: kotlin.String, pmail: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("address", listOf(address.toString()))
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/quarantine/blacklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
