/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pmg.models.PmgError
import com.clientapi.pmg.models.PmgQuarantineListEnum
import com.clientapi.pmg.models.PmgQuarantineQuarantineTypeEnum
import com.clientapi.pmg.models.QuarantineAttachmentResponse
import com.clientapi.pmg.models.QuarantineDownloadResponse
import com.clientapi.pmg.models.QuarantineGetQuarantineResponse
import com.clientapi.pmg.models.QuarantineListattachmentsResponse
import com.clientapi.pmg.models.QuarantineQuarusersResponse
import com.clientapi.pmg.models.QuarantineSendlinkRequest
import com.clientapi.pmg.models.QuarantineSendlinkResponse
import com.clientapi.pmg.models.QuarantineSpamResponse
import com.clientapi.pmg.models.QuarantineSpamstatusResponse
import com.clientapi.pmg.models.QuarantineSpamusersResponse
import com.clientapi.pmg.models.QuarantineVirusResponse
import com.clientapi.pmg.models.QuarantineVirusstatusResponse

import com.squareup.moshi.Json

import com.clientapi.pmg.infrastructure.ApiClient
import com.clientapi.pmg.infrastructure.ApiResponse
import com.clientapi.pmg.infrastructure.ClientException
import com.clientapi.pmg.infrastructure.ClientError
import com.clientapi.pmg.infrastructure.ServerException
import com.clientapi.pmg.infrastructure.ServerError
import com.clientapi.pmg.infrastructure.MultiValueMap
import com.clientapi.pmg.infrastructure.PartConfig
import com.clientapi.pmg.infrastructure.RequestConfig
import com.clientapi.pmg.infrastructure.RequestMethod
import com.clientapi.pmg.infrastructure.ResponseType
import com.clientapi.pmg.infrastructure.Success
import com.clientapi.pmg.infrastructure.toMultiValue

open class QuarantineApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /quarantine/attachment
     * Get a list of quarantined attachment mails in the given timeframe (default the last 24 hours)
     * Get a list of quarantined attachment mails in the given timeframe (default the last 24 hours).
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return QuarantineAttachmentResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineAttachment(endtime: kotlin.Long? = null, pmail: kotlin.String? = null, starttime: kotlin.Long? = null) : QuarantineAttachmentResponse {
        val localVarResponse = quarantineAttachmentWithHttpInfo(endtime = endtime, pmail = pmail, starttime = starttime)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineAttachmentResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/attachment
     * Get a list of quarantined attachment mails in the given timeframe (default the last 24 hours)
     * Get a list of quarantined attachment mails in the given timeframe (default the last 24 hours).
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return ApiResponse<QuarantineAttachmentResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineAttachmentWithHttpInfo(endtime: kotlin.Long?, pmail: kotlin.String?, starttime: kotlin.Long?) : ApiResponse<QuarantineAttachmentResponse?> {
        val localVariableConfig = quarantineAttachmentRequestConfig(endtime = endtime, pmail = pmail, starttime = starttime)

        return request<Unit, QuarantineAttachmentResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineAttachment
     *
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return RequestConfig
     */
    fun quarantineAttachmentRequestConfig(endtime: kotlin.Long?, pmail: kotlin.String?, starttime: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endtime != null) {
                    put("endtime", listOf(endtime.toString()))
                }
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
                if (starttime != null) {
                    put("starttime", listOf(starttime.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/attachment",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/download
     * Download E-Mail or Attachment from Quarantine
     * Download E-Mail or Attachment from Quarantine.
     * @param mailid Unique ID
     * @param attachmentid The Attachment ID for the mail. (optional)
     * @return QuarantineDownloadResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineDownload(mailid: kotlin.String, attachmentid: kotlin.Long? = null) : QuarantineDownloadResponse {
        val localVarResponse = quarantineDownloadWithHttpInfo(mailid = mailid, attachmentid = attachmentid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineDownloadResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/download
     * Download E-Mail or Attachment from Quarantine
     * Download E-Mail or Attachment from Quarantine.
     * @param mailid Unique ID
     * @param attachmentid The Attachment ID for the mail. (optional)
     * @return ApiResponse<QuarantineDownloadResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineDownloadWithHttpInfo(mailid: kotlin.String, attachmentid: kotlin.Long?) : ApiResponse<QuarantineDownloadResponse?> {
        val localVariableConfig = quarantineDownloadRequestConfig(mailid = mailid, attachmentid = attachmentid)

        return request<Unit, QuarantineDownloadResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineDownload
     *
     * @param mailid Unique ID
     * @param attachmentid The Attachment ID for the mail. (optional)
     * @return RequestConfig
     */
    fun quarantineDownloadRequestConfig(mailid: kotlin.String, attachmentid: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (attachmentid != null) {
                    put("attachmentid", listOf(attachmentid.toString()))
                }
                put("mailid", listOf(mailid.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/download",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine
     * Directory index
     * Directory index.
     * @return QuarantineGetQuarantineResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineGetQuarantine() : QuarantineGetQuarantineResponse {
        val localVarResponse = quarantineGetQuarantineWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineGetQuarantineResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine
     * Directory index
     * Directory index.
     * @return ApiResponse<QuarantineGetQuarantineResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineGetQuarantineWithHttpInfo() : ApiResponse<QuarantineGetQuarantineResponse?> {
        val localVariableConfig = quarantineGetQuarantineRequestConfig()

        return request<Unit, QuarantineGetQuarantineResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineGetQuarantine
     *
     * @return RequestConfig
     */
    fun quarantineGetQuarantineRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/listattachments
     * Get Attachments for E-Mail in Quarantine
     * Get Attachments for E-Mail in Quarantine.
     * @param id Unique ID
     * @return QuarantineListattachmentsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineListattachments(id: kotlin.String) : QuarantineListattachmentsResponse {
        val localVarResponse = quarantineListattachmentsWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineListattachmentsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/listattachments
     * Get Attachments for E-Mail in Quarantine
     * Get Attachments for E-Mail in Quarantine.
     * @param id Unique ID
     * @return ApiResponse<QuarantineListattachmentsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineListattachmentsWithHttpInfo(id: kotlin.String) : ApiResponse<QuarantineListattachmentsResponse?> {
        val localVariableConfig = quarantineListattachmentsRequestConfig(id = id)

        return request<Unit, QuarantineListattachmentsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineListattachments
     *
     * @param id Unique ID
     * @return RequestConfig
     */
    fun quarantineListattachmentsRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("id", listOf(id.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/listattachments",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/quarusers
     * Get a list of users with welcomelist/blocklist settings
     * Get a list of users with welcomelist/blocklist settings.
     * @param list If set, limits the result to the given list. (optional)
     * @return QuarantineQuarusersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineQuarusers(list: PmgQuarantineListEnum? = null) : QuarantineQuarusersResponse {
        val localVarResponse = quarantineQuarusersWithHttpInfo(list = list)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineQuarusersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/quarusers
     * Get a list of users with welcomelist/blocklist settings
     * Get a list of users with welcomelist/blocklist settings.
     * @param list If set, limits the result to the given list. (optional)
     * @return ApiResponse<QuarantineQuarusersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineQuarusersWithHttpInfo(list: PmgQuarantineListEnum?) : ApiResponse<QuarantineQuarusersResponse?> {
        val localVariableConfig = quarantineQuarusersRequestConfig(list = list)

        return request<Unit, QuarantineQuarusersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineQuarusers
     *
     * @param list If set, limits the result to the given list. (optional)
     * @return RequestConfig
     */
    fun quarantineQuarusersRequestConfig(list: PmgQuarantineListEnum?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (list != null) {
                    put("list", listOf(list.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/quarusers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /quarantine/sendlink
     * Send Quarantine link to given e-mail
     * Send Quarantine link to given e-mail.
     * @param quarantineSendlinkRequest 
     * @return QuarantineSendlinkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineSendlink(quarantineSendlinkRequest: QuarantineSendlinkRequest) : QuarantineSendlinkResponse {
        val localVarResponse = quarantineSendlinkWithHttpInfo(quarantineSendlinkRequest = quarantineSendlinkRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineSendlinkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /quarantine/sendlink
     * Send Quarantine link to given e-mail
     * Send Quarantine link to given e-mail.
     * @param quarantineSendlinkRequest 
     * @return ApiResponse<QuarantineSendlinkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineSendlinkWithHttpInfo(quarantineSendlinkRequest: QuarantineSendlinkRequest) : ApiResponse<QuarantineSendlinkResponse?> {
        val localVariableConfig = quarantineSendlinkRequestConfig(quarantineSendlinkRequest = quarantineSendlinkRequest)

        return request<QuarantineSendlinkRequest, QuarantineSendlinkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineSendlink
     *
     * @param quarantineSendlinkRequest 
     * @return RequestConfig
     */
    fun quarantineSendlinkRequestConfig(quarantineSendlinkRequest: QuarantineSendlinkRequest) : RequestConfig<QuarantineSendlinkRequest> {
        val localVariableBody = quarantineSendlinkRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/quarantine/sendlink",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/spam
     * Get a list of quarantined spam mails in the given timeframe (default the last 24 hours) for the given user
     * Get a list of quarantined spam mails in the given timeframe (default the last 24 hours) for the given user.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return QuarantineSpamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineSpam(endtime: kotlin.Long? = null, pmail: kotlin.String? = null, starttime: kotlin.Long? = null) : QuarantineSpamResponse {
        val localVarResponse = quarantineSpamWithHttpInfo(endtime = endtime, pmail = pmail, starttime = starttime)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineSpamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/spam
     * Get a list of quarantined spam mails in the given timeframe (default the last 24 hours) for the given user
     * Get a list of quarantined spam mails in the given timeframe (default the last 24 hours) for the given user.
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return ApiResponse<QuarantineSpamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineSpamWithHttpInfo(endtime: kotlin.Long?, pmail: kotlin.String?, starttime: kotlin.Long?) : ApiResponse<QuarantineSpamResponse?> {
        val localVariableConfig = quarantineSpamRequestConfig(endtime = endtime, pmail = pmail, starttime = starttime)

        return request<Unit, QuarantineSpamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineSpam
     *
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return RequestConfig
     */
    fun quarantineSpamRequestConfig(endtime: kotlin.Long?, pmail: kotlin.String?, starttime: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endtime != null) {
                    put("endtime", listOf(endtime.toString()))
                }
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
                if (starttime != null) {
                    put("starttime", listOf(starttime.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/spam",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/spamstatus
     * Get Spam Quarantine Status
     * Get Spam Quarantine Status
     * @return QuarantineSpamstatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineSpamstatus() : QuarantineSpamstatusResponse {
        val localVarResponse = quarantineSpamstatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineSpamstatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/spamstatus
     * Get Spam Quarantine Status
     * Get Spam Quarantine Status
     * @return ApiResponse<QuarantineSpamstatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineSpamstatusWithHttpInfo() : ApiResponse<QuarantineSpamstatusResponse?> {
        val localVariableConfig = quarantineSpamstatusRequestConfig()

        return request<Unit, QuarantineSpamstatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineSpamstatus
     *
     * @return RequestConfig
     */
    fun quarantineSpamstatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/spamstatus",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/spamusers
     * Get a list of receivers of spam in the given timespan (Default the last 24 hours)
     * Get a list of receivers of spam in the given timespan (Default the last 24 hours).
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param quarantineType Query this type of quarantine for users. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return QuarantineSpamusersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineSpamusers(endtime: kotlin.Long? = null, quarantineType: PmgQuarantineQuarantineTypeEnum? = null, starttime: kotlin.Long? = null) : QuarantineSpamusersResponse {
        val localVarResponse = quarantineSpamusersWithHttpInfo(endtime = endtime, quarantineType = quarantineType, starttime = starttime)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineSpamusersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/spamusers
     * Get a list of receivers of spam in the given timespan (Default the last 24 hours)
     * Get a list of receivers of spam in the given timespan (Default the last 24 hours).
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param quarantineType Query this type of quarantine for users. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return ApiResponse<QuarantineSpamusersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineSpamusersWithHttpInfo(endtime: kotlin.Long?, quarantineType: PmgQuarantineQuarantineTypeEnum?, starttime: kotlin.Long?) : ApiResponse<QuarantineSpamusersResponse?> {
        val localVariableConfig = quarantineSpamusersRequestConfig(endtime = endtime, quarantineType = quarantineType, starttime = starttime)

        return request<Unit, QuarantineSpamusersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineSpamusers
     *
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param quarantineType Query this type of quarantine for users. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return RequestConfig
     */
    fun quarantineSpamusersRequestConfig(endtime: kotlin.Long?, quarantineType: PmgQuarantineQuarantineTypeEnum?, starttime: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endtime != null) {
                    put("endtime", listOf(endtime.toString()))
                }
                if (quarantineType != null) {
                    put("quarantine-type", listOf(quarantineType.toString()))
                }
                if (starttime != null) {
                    put("starttime", listOf(starttime.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/spamusers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/virus
     * Get a list of quarantined virus mails in the given timeframe (default the last 24 hours)
     * Get a list of quarantined virus mails in the given timeframe (default the last 24 hours).
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return QuarantineVirusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineVirus(endtime: kotlin.Long? = null, pmail: kotlin.String? = null, starttime: kotlin.Long? = null) : QuarantineVirusResponse {
        val localVarResponse = quarantineVirusWithHttpInfo(endtime = endtime, pmail = pmail, starttime = starttime)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineVirusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/virus
     * Get a list of quarantined virus mails in the given timeframe (default the last 24 hours)
     * Get a list of quarantined virus mails in the given timeframe (default the last 24 hours).
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return ApiResponse<QuarantineVirusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineVirusWithHttpInfo(endtime: kotlin.Long?, pmail: kotlin.String?, starttime: kotlin.Long?) : ApiResponse<QuarantineVirusResponse?> {
        val localVariableConfig = quarantineVirusRequestConfig(endtime = endtime, pmail = pmail, starttime = starttime)

        return request<Unit, QuarantineVirusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineVirus
     *
     * @param endtime Only consider entries older than &#39;endtime&#39; (unix epoch). This is set to &#39;&lt;start&gt; + 1day&#39; by default. (optional)
     * @param pmail List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles. (optional)
     * @param starttime Only consider entries newer than &#39;starttime&#39; (unix epoch). Default is &#39;now - 1day&#39;. (optional)
     * @return RequestConfig
     */
    fun quarantineVirusRequestConfig(endtime: kotlin.Long?, pmail: kotlin.String?, starttime: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endtime != null) {
                    put("endtime", listOf(endtime.toString()))
                }
                if (pmail != null) {
                    put("pmail", listOf(pmail.toString()))
                }
                if (starttime != null) {
                    put("starttime", listOf(starttime.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/virus",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /quarantine/virusstatus
     * Get Virus Quarantine Status
     * Get Virus Quarantine Status
     * @return QuarantineVirusstatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun quarantineVirusstatus() : QuarantineVirusstatusResponse {
        val localVarResponse = quarantineVirusstatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as QuarantineVirusstatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /quarantine/virusstatus
     * Get Virus Quarantine Status
     * Get Virus Quarantine Status
     * @return ApiResponse<QuarantineVirusstatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun quarantineVirusstatusWithHttpInfo() : ApiResponse<QuarantineVirusstatusResponse?> {
        val localVariableConfig = quarantineVirusstatusRequestConfig()

        return request<Unit, QuarantineVirusstatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quarantineVirusstatus
     *
     * @return RequestConfig
     */
    fun quarantineVirusstatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/quarantine/virusstatus",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
