// Auto-generated by scripts/sdk-facades.ts. Do not edit.

package com.clientapi.pmg

import okhttp3.Call
import com.clientapi.pmg.infrastructure.ApiClient

class Pmg(
    basePath: String =
        System.getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json"),
    httpClient: Call.Factory = ApiClient.defaultClient,
) : Client(basePath, httpClient)
