/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param password The secret password. This can also be a valid ticket.
 * @param username User name
 * @param otp One-time password for Two-factor authentication.
 * @param path Verify ticket, and check if user have access on 'path'
 * @param realm You can optionally pass the realm using this parameter. Normally the realm is simply added to the username <username>@<relam>.
 * @param tfaChallenge The signed TFA challenge string the user wants to respond to.
 */


data class AccessTicketCreateTicketRequest (

    /* The secret password. This can also be a valid ticket. */
    @Json(name = "password")
    val password: kotlin.String,

    /* User name */
    @Json(name = "username")
    val username: kotlin.String,

    /* One-time password for Two-factor authentication. */
    @Json(name = "otp")
    val otp: kotlin.String? = null,

    /* Verify ticket, and check if user have access on 'path' */
    @Json(name = "path")
    val path: kotlin.String? = null,

    /* You can optionally pass the realm using this parameter. Normally the realm is simply added to the username <username>@<relam>. */
    @Json(name = "realm")
    val realm: kotlin.String? = null,

    /* The signed TFA challenge string the user wants to respond to. */
    @Json(name = "tfa-challenge")
    val tfaChallenge: kotlin.String? = null

) {


}

