/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param realm 
 * @param type 
 * @param comment A comment. The GUI use this text when you select a authentication realm on the login window.
 */


data class AccessAuthRealmGetAuthRealmResponseDataInner (

    @Json(name = "realm")
    val realm: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    /* A comment. The GUI use this text when you select a authentication realm on the login window. */
    @Json(name = "comment")
    val comment: kotlin.String? = null

) {


}

