/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code OpenId Connect authorization code.
 * @param redirectUrl Redirection Url. The client should set this to the used server url (location.origin).
 * @param state OpenId Connect state.
 */


data class AccessOidcLoginRequest (

    /* OpenId Connect authorization code. */
    @Json(name = "code")
    val code: kotlin.String,

    /* Redirection Url. The client should set this to the used server url (location.origin). */
    @Json(name = "redirect-url")
    val redirectUrl: kotlin.String,

    /* OpenId Connect state. */
    @Json(name = "state")
    val state: kotlin.String

) {


}

