/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enable 
 * @param role 
 * @param userid 
 * @param comment 
 * @param tfaLockedUntil Contains a timestamp until when a user is locked out of 2nd factors.
 * @param totpLocked True if the user is currently locked out of TOTP factors.
 */


data class AccessUsersGetUsersResponseDataInner (

    @Json(name = "enable")
    val enable: PmgBoolean,

    @Json(name = "role")
    val role: kotlin.String,

    @Json(name = "userid")
    val userid: kotlin.String,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Contains a timestamp until when a user is locked out of 2nd factors. */
    @Json(name = "tfa-locked-until")
    val tfaLockedUntil: kotlin.Long? = null,

    /* True if the user is currently locked out of TOTP factors. */
    @Json(name = "totp-locked")
    val totpLocked: PmgBoolean? = null

) {


}

