/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgAccessAuthRealmTypeEnum
import com.clientapi.pmg.models.PmgAutocreateRoleAssignmentField
import com.clientapi.pmg.models.PmgAutocreateRoleEnum
import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param realm Authentication domain ID
 * @param type Realm type.
 * @param acrValues Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request.
 * @param autocreate Automatically create users if they do not exist.
 * @param autocreateRole Automatically create users with a specific role. NOTE: Deprecated, favor 'autocreate-role-assignment'
 * @param autocreateRoleAssignment Defines which role should be assigned to auto-created users.
 * @param clientId OpenID Connect Client ID
 * @param clientKey OpenID Connect Client Key
 * @param comment Description.
 * @param default Use this as default realm
 * @param issuerUrl OpenID Connect Issuer Url
 * @param prompt Specifies whether the Authorization Server prompts the End-User for reauthentication and consent.
 * @param scopes Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'.
 * @param usernameClaim OpenID Connect claim used to generate the unique username.
 */


data class AccessAuthRealmCreateAuthRealmRequest (

    /* Authentication domain ID */
    @Json(name = "realm")
    val realm: kotlin.String,

    /* Realm type. */
    @Json(name = "type")
    val type: PmgAccessAuthRealmTypeEnum,

    /* Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request. */
    @Json(name = "acr-values")
    val acrValues: kotlin.String? = null,

    /* Automatically create users if they do not exist. */
    @Json(name = "autocreate")
    val autocreate: PmgBoolean? = null,

    /* Automatically create users with a specific role. NOTE: Deprecated, favor 'autocreate-role-assignment' */
    @Json(name = "autocreate-role")
    val autocreateRole: PmgAutocreateRoleEnum? = null,

    /* Defines which role should be assigned to auto-created users. */
    @Json(name = "autocreate-role-assignment")
    val autocreateRoleAssignment: PmgAutocreateRoleAssignmentField? = null,

    /* OpenID Connect Client ID */
    @Json(name = "client-id")
    val clientId: kotlin.String? = null,

    /* OpenID Connect Client Key */
    @Json(name = "client-key")
    val clientKey: kotlin.String? = null,

    /* Description. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Use this as default realm */
    @Json(name = "default")
    val default: PmgBoolean? = null,

    /* OpenID Connect Issuer Url */
    @Json(name = "issuer-url")
    val issuerUrl: kotlin.String? = null,

    /* Specifies whether the Authorization Server prompts the End-User for reauthentication and consent. */
    @Json(name = "prompt")
    val prompt: kotlin.String? = null,

    /* Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'. */
    @Json(name = "scopes")
    val scopes: kotlin.String? = "email profile",

    /* OpenID Connect claim used to generate the unique username. */
    @Json(name = "username-claim")
    val usernameClaim: kotlin.String? = "sub"

) {


}

