/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.AccessTfaListTfaResponseDataInnerEntriesInner
import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyEntries 
 * @param userid User this entry belongs to.
 * @param tfaLockedUntil Contains a timestamp until when a user is locked out of 2nd factors.
 * @param totpLocked True if the user is currently locked out of TOTP factors.
 */


data class AccessTfaListTfaResponseDataInner (

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<AccessTfaListTfaResponseDataInnerEntriesInner>,

    /* User this entry belongs to. */
    @Json(name = "userid")
    val userid: kotlin.String,

    /* Contains a timestamp until when a user is locked out of 2nd factors. */
    @Json(name = "tfa-locked-until")
    val tfaLockedUntil: kotlin.Long? = null,

    /* True if the user is currently locked out of TOTP factors. */
    @Json(name = "totp-locked")
    val totpLocked: PmgBoolean? = null

) {


}

