/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description A description to distinguish multiple entries from one another
 * @param enable Whether the entry should be enabled for login.
 * @param password The current password.
 */


data class AccessTfaUpdateTfaEntryRequest (

    /* A description to distinguish multiple entries from one another */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Whether the entry should be enabled for login. */
    @Json(name = "enable")
    val enable: PmgBoolean? = null,

    /* The current password. */
    @Json(name = "password")
    val password: kotlin.String? = null

) {


}

