/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `field` The Field
 * @param `value` The Value
 * @param info Informational comment.
 * @param name Action name.
 */


data class ConfigRuledbUpdateFieldRequest (

    /* The Field */
    @Json(name = "field")
    val `field`: kotlin.String,

    /* The Value */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* Informational comment. */
    @Json(name = "info")
    val info: kotlin.String? = null,

    /* Action name. */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

