/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param active 
 * @param direction 
 * @param id 
 * @param name 
 * @param priority 
 */


data class ConfigRuledbConfigResponseData (

    @Json(name = "active")
    val active: PmgBoolean,

    @Json(name = "direction")
    val direction: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "priority")
    val priority: kotlin.Long

) {


}

