/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param disable 
 * @param mode 
 * @param profile 
 * @param server1 
 * @param comment 
 * @param gcount 
 * @param mcount 
 * @param server2 
 * @param ucount 
 */


data class ConfigLdapGetLdapResponseDataInner (

    @Json(name = "disable")
    val disable: PmgBoolean,

    @Json(name = "mode")
    val mode: kotlin.String,

    @Json(name = "profile")
    val profile: kotlin.String,

    @Json(name = "server1")
    val server1: kotlin.String,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "gcount")
    val gcount: kotlin.Long? = null,

    @Json(name = "mcount")
    val mcount: kotlin.Long? = null,

    @Json(name = "server2")
    val server2: kotlin.String? = null,

    @Json(name = "ucount")
    val ucount: kotlin.Long? = null

) {


}

