/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param archiveblockencrypted Whether to mark encrypted archives and documents as heuristic virus match. A match does not necessarily result in an immediate block, it just raises the Spam Score by 'clamav_heuristic_score'.
 * @param archivemaxfiles Number of files to be scanned within an archive, a document, or any other kind of container. Warning: disabling this limit or setting it too high may result in severe damage to the system.
 * @param archivemaxrec Nested archives are scanned recursively, e.g. if a ZIP archive contains a TAR  file,  all files within it will also be scanned. This options specifies how deeply the process should be continued. Warning: setting this limit too high may result in severe damage to the system.
 * @param archivemaxsize Files larger than this limit (in bytes) won't be scanned.
 * @param dbmirror ClamAV database mirror server.
 * @param delete A list of settings you want to delete.
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 * @param maxcccount This option sets the lowest number of Credit Card or Social Security numbers found in a file to generate a detect.
 * @param maxscansize Sets the maximum amount of data (in bytes) to be scanned for each input file.
 * @param scriptedupdates Enables ScriptedUpdates (incremental download of signatures)
 */


data class ConfigClamavUpdateClamavSectionRequest (

    /* Whether to mark encrypted archives and documents as heuristic virus match. A match does not necessarily result in an immediate block, it just raises the Spam Score by 'clamav_heuristic_score'. */
    @Json(name = "archiveblockencrypted")
    val archiveblockencrypted: PmgBoolean? = null,

    /* Number of files to be scanned within an archive, a document, or any other kind of container. Warning: disabling this limit or setting it too high may result in severe damage to the system. */
    @Json(name = "archivemaxfiles")
    val archivemaxfiles: kotlin.Long? = 1000L,

    /* Nested archives are scanned recursively, e.g. if a ZIP archive contains a TAR  file,  all files within it will also be scanned. This options specifies how deeply the process should be continued. Warning: setting this limit too high may result in severe damage to the system. */
    @Json(name = "archivemaxrec")
    val archivemaxrec: kotlin.Long? = 5L,

    /* Files larger than this limit (in bytes) won't be scanned. */
    @Json(name = "archivemaxsize")
    val archivemaxsize: kotlin.Long? = 25000000L,

    /* ClamAV database mirror server. */
    @Json(name = "dbmirror")
    val dbmirror: kotlin.String? = "database.clamav.net",

    /* A list of settings you want to delete. */
    @Json(name = "delete")
    val delete: kotlin.String? = null,

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* This option sets the lowest number of Credit Card or Social Security numbers found in a file to generate a detect. */
    @Json(name = "maxcccount")
    val maxcccount: kotlin.Long? = 0L,

    /* Sets the maximum amount of data (in bytes) to be scanned for each input file. */
    @Json(name = "maxscansize")
    val maxscansize: kotlin.Long? = 100000000L,

    /* Enables ScriptedUpdates (incremental download of signatures) */
    @Json(name = "scriptedupdates")
    val scriptedupdates: PmgBoolean? = null

) {


}

