/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean
import com.clientapi.pmg.models.PmgConfigMailProtocolEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment Comment.
 * @param host Target host (name or IP address).
 * @param port Transport port.
 * @param protocol Transport protocol.
 * @param useMx Enable MX lookups (SMTP).
 */


data class ConfigTransportWriteRequest (

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Target host (name or IP address). */
    @Json(name = "host")
    val host: kotlin.String? = null,

    /* Transport port. */
    @Json(name = "port")
    val port: kotlin.Int? = null,

    /* Transport protocol. */
    @Json(name = "protocol")
    val protocol: PmgConfigMailProtocolEnum? = null,

    /* Enable MX lookups (SMTP). */
    @Json(name = "use_mx")
    val useMx: PmgBoolean? = null

) {


}

