/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment 
 * @param domain 
 * @param host 
 * @param port 
 * @param protocol 
 * @param useMx 
 */


data class ConfigTransportGetTransportResponseDataInner (

    @Json(name = "comment")
    val comment: kotlin.String,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "host")
    val host: kotlin.String,

    @Json(name = "port")
    val port: kotlin.Long,

    @Json(name = "protocol")
    val protocol: kotlin.String,

    @Json(name = "use_mx")
    val useMx: PmgBoolean

) {


}

