/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean
import com.clientapi.pmg.models.PmgModeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param profile Profile ID.
 * @param server1 Server address.
 * @param accountattr Account attribute name name.
 * @param basedn Base domain name.
 * @param binddn Bind domain name.
 * @param bindpw Bind password.
 * @param cafile Path to CA file. Only useful with option 'verify'
 * @param comment Description.
 * @param disable Flag to disable/deactivate the entry.
 * @param filter LDAP filter.
 * @param groupbasedn Base domain name for groups.
 * @param groupclass List of objectclasses for groups.
 * @param mailattr List of mail attribute names.
 * @param mode LDAP protocol mode ('ldap', 'ldaps' or 'ldap+starttls').
 * @param port Specify the port to connect to.
 * @param server2 Fallback server address. Userd when the first server is not available.
 * @param verify Verify server certificate. Only useful with ldaps or ldap+starttls.
 */


data class ConfigLdapCreateLdapRequest (

    /* Profile ID. */
    @Json(name = "profile")
    val profile: kotlin.String,

    /* Server address. */
    @Json(name = "server1")
    val server1: kotlin.String,

    /* Account attribute name name. */
    @Json(name = "accountattr")
    val accountattr: kotlin.String? = "sAMAccountName, uid",

    /* Base domain name. */
    @Json(name = "basedn")
    val basedn: kotlin.String? = null,

    /* Bind domain name. */
    @Json(name = "binddn")
    val binddn: kotlin.String? = null,

    /* Bind password. */
    @Json(name = "bindpw")
    val bindpw: kotlin.String? = null,

    /* Path to CA file. Only useful with option 'verify' */
    @Json(name = "cafile")
    val cafile: kotlin.String? = null,

    /* Description. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Flag to disable/deactivate the entry. */
    @Json(name = "disable")
    val disable: PmgBoolean? = null,

    /* LDAP filter. */
    @Json(name = "filter")
    val filter: kotlin.String? = null,

    /* Base domain name for groups. */
    @Json(name = "groupbasedn")
    val groupbasedn: kotlin.String? = null,

    /* List of objectclasses for groups. */
    @Json(name = "groupclass")
    val groupclass: kotlin.String? = "group, univentionGroup, ipausergroup",

    /* List of mail attribute names. */
    @Json(name = "mailattr")
    val mailattr: kotlin.String? = "mail, userPrincipalName, proxyAddresses, othermailbox, mailAlternativeAddress",

    /* LDAP protocol mode ('ldap', 'ldaps' or 'ldap+starttls'). */
    @Json(name = "mode")
    val mode: PmgModeEnum? = null,

    /* Specify the port to connect to. */
    @Json(name = "port")
    val port: kotlin.Int? = null,

    /* Fallback server address. Userd when the first server is not available. */
    @Json(name = "server2")
    val server2: kotlin.String? = null,

    /* Verify server certificate. Only useful with ldaps or ldap+starttls. */
    @Json(name = "verify")
    val verify: PmgBoolean? = null

) {


}

