/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean
import com.clientapi.pmg.models.PmgConfigMailProtocolEnum
import com.clientapi.pmg.models.PmgConfigMailVerifyreceiversEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param acceptBrokenMime Accept e-mails with broken MIME structure (insecure). If enabled, a `X-Proxmox-Broken-Message` header is added to each mail with broken MIME structure.
 * @param banner ESMTP banner.
 * @param beforeQueueFiltering Enable before queue filtering by pmg-smtp-filter
 * @param connCountLimit How many simultaneous connections any client is allowed to make to this service. To disable this feature, specify a limit of 0.
 * @param connRateLimit The maximal number of connection attempts any client is allowed to make to this service per minute. To disable this feature, specify a limit of 0.
 * @param delete A list of settings you want to delete.
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 * @param dnsblSites Optional list of DNS welcome/blocklist domains (postfix option `postscreen_dnsbl_sites`).
 * @param dnsblThreshold The inclusive lower bound for blocking a remote SMTP client, based on its combined DNSBL score (postfix option `postscreen_dnsbl_threshold`).
 * @param dwarning SMTP delay warning time (in hours). (postfix option `delay_warning_time`)
 * @param extPort SMTP port number for incoming mail (untrusted). This must be a different number than 'int_port'.
 * @param filterTimeout Timeout for the processing of one mail (in seconds)  (postfix option `smtpd_proxy_timeout` and `lmtp_data_done_timeout`)
 * @param greylist Use Greylisting for IPv4.
 * @param greylist6 Use Greylisting for IPv6.
 * @param greylistmask4 Netmask to apply for greylisting IPv4 hosts
 * @param greylistmask6 Netmask to apply for greylisting IPv6 hosts
 * @param helotests Use SMTP HELO tests. (postfix option `smtpd_helo_restrictions`)
 * @param hideReceived Hide received header in outgoing mails.
 * @param intPort SMTP port number for outgoing mail (trusted).
 * @param maxFilters Maximum number of pmg-smtp-filter processes.
 * @param maxPolicy Maximum number of pmgpolicy processes.
 * @param maxSmtpdIn Maximum number of SMTP daemon processes (in).
 * @param maxSmtpdOut Maximum number of SMTP daemon processes (out).
 * @param maxsize Maximum email size. Larger mails are rejected. (postfix option `message_size_limit`)
 * @param messageRateLimit The maximal number of message delivery requests that any client is allowed to make to this service per minute.To disable this feature, specify a limit of 0.
 * @param ndrOnBlock Send out NDR when mail gets blocked
 * @param rejectunknown Reject unknown clients. (postfix option `reject_unknown_client_hostname`)
 * @param rejectunknownsender Reject unknown senders. (postfix option `reject_unknown_sender_domain`)
 * @param relay The default mail delivery transport (incoming mails).
 * @param relaynomx Disable MX lookups for default relay (SMTP only, ignored for LMTP).
 * @param relayport SMTP/LMTP port number for relay host.
 * @param relayprotocol Transport protocol for relay host.
 * @param smarthost When set, all outgoing mails are delivered to the specified smarthost. (postfix option `default_transport`)
 * @param smarthostport SMTP port number for smarthost. (postfix option `default_transport`)
 * @param smtputf8 Enable SMTPUTF8 support in Postfix and detection for locally generated mail (postfix option `smtputf8_enable`)
 * @param spf Use Sender Policy Framework.
 * @param tls Enable TLS.
 * @param tlsheader Add TLS received header.
 * @param tlslog Enable TLS Logging.
 * @param verifyreceivers Enable receiver verification. The value specifies the numerical reply code when the Postfix SMTP server rejects a recipient address. (postfix options `reject_unknown_recipient_domain`, `reject_unverified_recipient`, and `unverified_recipient_reject_code`)
 */


data class ConfigMailUpdateMailSectionRequest (

    /* Accept e-mails with broken MIME structure (insecure). If enabled, a `X-Proxmox-Broken-Message` header is added to each mail with broken MIME structure. */
    @Json(name = "accept-broken-mime")
    val acceptBrokenMime: PmgBoolean? = null,

    /* ESMTP banner. */
    @Json(name = "banner")
    val banner: kotlin.String? = "ESMTP Proxmox",

    /* Enable before queue filtering by pmg-smtp-filter */
    @Json(name = "before_queue_filtering")
    val beforeQueueFiltering: PmgBoolean? = null,

    /* How many simultaneous connections any client is allowed to make to this service. To disable this feature, specify a limit of 0. */
    @Json(name = "conn_count_limit")
    val connCountLimit: kotlin.Long? = 50L,

    /* The maximal number of connection attempts any client is allowed to make to this service per minute. To disable this feature, specify a limit of 0. */
    @Json(name = "conn_rate_limit")
    val connRateLimit: kotlin.Long? = 0L,

    /* A list of settings you want to delete. */
    @Json(name = "delete")
    val delete: kotlin.String? = null,

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Optional list of DNS welcome/blocklist domains (postfix option `postscreen_dnsbl_sites`). */
    @Json(name = "dnsbl_sites")
    val dnsblSites: kotlin.String? = null,

    /* The inclusive lower bound for blocking a remote SMTP client, based on its combined DNSBL score (postfix option `postscreen_dnsbl_threshold`). */
    @Json(name = "dnsbl_threshold")
    val dnsblThreshold: kotlin.Long? = 1L,

    /* SMTP delay warning time (in hours). (postfix option `delay_warning_time`) */
    @Json(name = "dwarning")
    val dwarning: kotlin.Long? = 4L,

    /* SMTP port number for incoming mail (untrusted). This must be a different number than 'int_port'. */
    @Json(name = "ext_port")
    val extPort: kotlin.Int? = 25,

    /* Timeout for the processing of one mail (in seconds)  (postfix option `smtpd_proxy_timeout` and `lmtp_data_done_timeout`) */
    @Json(name = "filter-timeout")
    val filterTimeout: kotlin.Int? = 600,

    /* Use Greylisting for IPv4. */
    @Json(name = "greylist")
    val greylist: PmgBoolean? = null,

    /* Use Greylisting for IPv6. */
    @Json(name = "greylist6")
    val greylist6: PmgBoolean? = null,

    /* Netmask to apply for greylisting IPv4 hosts */
    @Json(name = "greylistmask4")
    val greylistmask4: kotlin.Int? = 24,

    /* Netmask to apply for greylisting IPv6 hosts */
    @Json(name = "greylistmask6")
    val greylistmask6: kotlin.Int? = 64,

    /* Use SMTP HELO tests. (postfix option `smtpd_helo_restrictions`) */
    @Json(name = "helotests")
    val helotests: PmgBoolean? = null,

    /* Hide received header in outgoing mails. */
    @Json(name = "hide_received")
    val hideReceived: PmgBoolean? = null,

    /* SMTP port number for outgoing mail (trusted). */
    @Json(name = "int_port")
    val intPort: kotlin.Int? = 26,

    /* Maximum number of pmg-smtp-filter processes. */
    @Json(name = "max_filters")
    val maxFilters: kotlin.Int? = 25,

    /* Maximum number of pmgpolicy processes. */
    @Json(name = "max_policy")
    val maxPolicy: kotlin.Int? = 5,

    /* Maximum number of SMTP daemon processes (in). */
    @Json(name = "max_smtpd_in")
    val maxSmtpdIn: kotlin.Int? = 100,

    /* Maximum number of SMTP daemon processes (out). */
    @Json(name = "max_smtpd_out")
    val maxSmtpdOut: kotlin.Int? = 100,

    /* Maximum email size. Larger mails are rejected. (postfix option `message_size_limit`) */
    @Json(name = "maxsize")
    val maxsize: kotlin.Long? = 10485760L,

    /* The maximal number of message delivery requests that any client is allowed to make to this service per minute.To disable this feature, specify a limit of 0. */
    @Json(name = "message_rate_limit")
    val messageRateLimit: kotlin.Long? = 0L,

    /* Send out NDR when mail gets blocked */
    @Json(name = "ndr_on_block")
    val ndrOnBlock: PmgBoolean? = null,

    /* Reject unknown clients. (postfix option `reject_unknown_client_hostname`) */
    @Json(name = "rejectunknown")
    val rejectunknown: PmgBoolean? = null,

    /* Reject unknown senders. (postfix option `reject_unknown_sender_domain`) */
    @Json(name = "rejectunknownsender")
    val rejectunknownsender: PmgBoolean? = null,

    /* The default mail delivery transport (incoming mails). */
    @Json(name = "relay")
    val relay: kotlin.String? = null,

    /* Disable MX lookups for default relay (SMTP only, ignored for LMTP). */
    @Json(name = "relaynomx")
    val relaynomx: PmgBoolean? = null,

    /* SMTP/LMTP port number for relay host. */
    @Json(name = "relayport")
    val relayport: kotlin.Int? = 25,

    /* Transport protocol for relay host. */
    @Json(name = "relayprotocol")
    val relayprotocol: PmgConfigMailProtocolEnum? = null,

    /* When set, all outgoing mails are delivered to the specified smarthost. (postfix option `default_transport`) */
    @Json(name = "smarthost")
    val smarthost: kotlin.String? = null,

    /* SMTP port number for smarthost. (postfix option `default_transport`) */
    @Json(name = "smarthostport")
    val smarthostport: kotlin.Int? = 25,

    /* Enable SMTPUTF8 support in Postfix and detection for locally generated mail (postfix option `smtputf8_enable`) */
    @Json(name = "smtputf8")
    val smtputf8: PmgBoolean? = null,

    /* Use Sender Policy Framework. */
    @Json(name = "spf")
    val spf: PmgBoolean? = null,

    /* Enable TLS. */
    @Json(name = "tls")
    val tls: PmgBoolean? = null,

    /* Add TLS received header. */
    @Json(name = "tlsheader")
    val tlsheader: PmgBoolean? = null,

    /* Enable TLS Logging. */
    @Json(name = "tlslog")
    val tlslog: PmgBoolean? = null,

    /* Enable receiver verification. The value specifies the numerical reply code when the Postfix SMTP server rejects a recipient address. (postfix options `reject_unknown_recipient_domain`, `reject_unverified_recipient`, and `unverified_recipient_reject_code`) */
    @Json(name = "verifyreceivers")
    val verifyreceivers: PmgConfigMailVerifyreceiversEnum? = null

) {


}

