/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param text The replacement text.
 * @param all Remove all attachments
 * @param info Informational comment.
 * @param name Action name.
 * @param quarantine Copy original mail to attachment Quarantine.
 */


data class ConfigRuledbUpdateRemoveattachmentsRequest (

    /* The replacement text. */
    @Json(name = "text")
    val text: kotlin.String,

    /* Remove all attachments */
    @Json(name = "all")
    val all: PmgBoolean? = null,

    /* Informational comment. */
    @Json(name = "info")
    val info: kotlin.String? = null,

    /* Action name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Copy original mail to attachment Quarantine. */
    @Json(name = "quarantine")
    val quarantine: PmgBoolean? = null

) {


}

