/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param target Send a Blind Carbon Copy to this email address.
 * @param info Informational comment.
 * @param name Action name.
 * @param original Send the original, unmodified mail.
 */


data class ConfigRuledbUpdateBccRequest (

    /* Send a Blind Carbon Copy to this email address. */
    @Json(name = "target")
    val target: kotlin.String,

    /* Informational comment. */
    @Json(name = "info")
    val info: kotlin.String? = null,

    /* Action name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Send the original, unmodified mail. */
    @Json(name = "original")
    val original: PmgBoolean? = null

) {


}

