/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param end End time in `H:i` format (00:00).
 * @param start Start time in `H:i` format (00:00).
 */


data class ConfigRuledbTimeframeRequest (

    /* End time in `H:i` format (00:00). */
    @Json(name = "end")
    val end: kotlin.String,

    /* Start time in `H:i` format (00:00). */
    @Json(name = "start")
    val start: kotlin.String

) {


}

