/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param body The Notification Body
 * @param subject The Notification subject
 * @param to The Receiver E-Mail address
 * @param attach Attach original E-Mail
 * @param info Informational comment.
 * @param name Action name.
 */


data class ConfigRuledbUpdateNotificationRequest (

    /* The Notification Body */
    @Json(name = "body")
    val body: kotlin.String,

    /* The Notification subject */
    @Json(name = "subject")
    val subject: kotlin.String,

    /* The Receiver E-Mail address */
    @Json(name = "to")
    val to: kotlin.String,

    /* Attach original E-Mail */
    @Json(name = "attach")
    val attach: PmgBoolean? = null,

    /* Informational comment. */
    @Json(name = "info")
    val info: kotlin.String? = null,

    /* Action name. */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

