/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param score The score the rule should be valued at.
 * @param comment The Comment.
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 */


data class ConfigCustomscoresEditScoreRequest (

    /* The score the rule should be valued at. */
    @Json(name = "score")
    val score: java.math.BigDecimal,

    /* The Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null

) {


}

