/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 * @param restartDaemon If set, also restarts pmg-smtp-filter. This is necessary for the changes to work.
 */


data class ConfigCustomscoresApplyScoreChangesRequest (

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* If set, also restarts pmg-smtp-filter. This is necessary for the changes to work. */
    @Json(name = "restart-daemon")
    val restartDaemon: PmgBoolean? = null

) {


}

