/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cid 
 * @param fingerprint 
 * @param hostrsapubkey 
 * @param ip 
 * @param name 
 * @param rootrsapubkey 
 * @param type 
 */


data class ConfigClusterNodesResponseDataInner (

    @Json(name = "cid")
    val cid: kotlin.Long,

    @Json(name = "fingerprint")
    val fingerprint: kotlin.String,

    @Json(name = "hostrsapubkey")
    val hostrsapubkey: kotlin.String,

    @Json(name = "ip")
    val ip: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "rootrsapubkey")
    val rootrsapubkey: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String

) {


}

