/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param backupId 
 * @param backupTime 
 * @param ctime 
 * @param propertySize 
 */


data class NodesPbsGetSnapshotsResponseDataInner (

    @Json(name = "backup-id")
    val backupId: kotlin.String,

    @Json(name = "backup-time")
    val backupTime: kotlin.String,

    @Json(name = "ctime")
    val ctime: kotlin.String,

    @Json(name = "size")
    val propertySize: kotlin.Long

) {


}

