/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param node URL slug of the child resource (inferred from PVE HATEOAS link).
 * @param id Resource id of the form \"node/<name>\".
 * @param type Resource type discriminator.
 * @param disk Used disk space in bytes.
 * @param maxdisk Total disk space in bytes.
 */


data class NodesGetNodesResponseDataInner (

    /* URL slug of the child resource (inferred from PVE HATEOAS link). */
    @Json(name = "node")
    val node: kotlin.String,

    /* Resource id of the form \"node/<name>\". */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Resource type discriminator. */
    @Json(name = "type")
    val type: NodesGetNodesResponseDataInner.Type? = null,

    /* Used disk space in bytes. */
    @Json(name = "disk")
    val disk: kotlin.Long? = null,

    /* Total disk space in bytes. */
    @Json(name = "maxdisk")
    val maxdisk: kotlin.Long? = null

) {

    /**
     * Resource type discriminator.
     *
     * Values: NODE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "node") NODE("node");
    }

}

