/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.NodesStatusStatusResponseDataBootInfo
import com.clientapi.pmg.models.NodesStatusStatusResponseDataCurrentKernel
import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bootInfo 
 * @param currentKernel 
 * @param insync Database is synced with other nodes.
 * @param time Seconds since 1970-01-01 00:00:00 UTC.
 * @param uptime The uptime of the system in seconds.
 */


data class NodesStatusStatusResponseData (

    @Json(name = "boot-info")
    val bootInfo: NodesStatusStatusResponseDataBootInfo,

    @Json(name = "current-kernel")
    val currentKernel: NodesStatusStatusResponseDataCurrentKernel,

    /* Database is synced with other nodes. */
    @Json(name = "insync")
    val insync: PmgBoolean,

    /* Seconds since 1970-01-01 00:00:00 UTC. */
    @Json(name = "time")
    val time: kotlin.Long,

    /* The uptime of the system in seconds. */
    @Json(name = "uptime")
    val uptime: kotlin.Long

) {


}

