/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param config Restore system configuration.
 * @param database Restore the rule database. This is the default.
 * @param statistic Restore statistic databases. Only considered when you restore the 'database'.
 */


data class NodesBackupRestoreRequest (

    /* Restore system configuration. */
    @Json(name = "config")
    val config: PmgBoolean? = null,

    /* Restore the rule database. This is the default. */
    @Json(name = "database")
    val database: PmgBoolean? = null,

    /* Restore statistic databases. Only considered when you restore the 'database'. */
    @Json(name = "statistic")
    val statistic: PmgBoolean? = null

) {


}

