/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: BALANCE_RR,ACTIVE_BACKUP,BALANCE_XOR,BROADCAST,_802_PERIOD3AD,BALANCE_TLB,BALANCE_ALB,BALANCE_SLB,LACP_BALANCE_SLB,LACP_BALANCE_TCP
 */

@JsonClass(generateAdapter = false)
enum class PmgBondModeEnum(val value: kotlin.String) {

    @Json(name = "balance-rr")
    BALANCE_RR("balance-rr"),

    @Json(name = "active-backup")
    ACTIVE_BACKUP("active-backup"),

    @Json(name = "balance-xor")
    BALANCE_XOR("balance-xor"),

    @Json(name = "broadcast")
    BROADCAST("broadcast"),

    @Json(name = "802.3ad")
    _802_PERIOD3AD("802.3ad"),

    @Json(name = "balance-tlb")
    BALANCE_TLB("balance-tlb"),

    @Json(name = "balance-alb")
    BALANCE_ALB("balance-alb"),

    @Json(name = "balance-slb")
    BALANCE_SLB("balance-slb"),

    @Json(name = "lacp-balance-slb")
    LACP_BALANCE_SLB("lacp-balance-slb"),

    @Json(name = "lacp-balance-tcp")
    LACP_BALANCE_TCP("lacp-balance-tcp");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PmgBondModeEnum) "$data" else null

        /**
         * Returns a valid [PmgBondModeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PmgBondModeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

