/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: ALLOW_SUBDOMAINS,ID,ORIGIN,RP
 */

@JsonClass(generateAdapter = false)
enum class PmgConfigTfaDeleteEnum(val value: kotlin.String) {

    @Json(name = "allow-subdomains")
    ALLOW_SUBDOMAINS("allow-subdomains"),

    @Json(name = "id")
    ID("id"),

    @Json(name = "origin")
    ORIGIN("origin"),

    @Json(name = "rp")
    RP("rp");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PmgConfigTfaDeleteEnum) "$data" else null

        /**
         * Returns a valid [PmgConfigTfaDeleteEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PmgConfigTfaDeleteEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

