/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: WELCOMELIST,BLOCKLIST,WHITELIST,BLACKLIST,DELIVER,DELETE
 */

@JsonClass(generateAdapter = false)
enum class PmgQuarantineContentActionEnum(val value: kotlin.String) {

    @Json(name = "welcomelist")
    WELCOMELIST("welcomelist"),

    @Json(name = "blocklist")
    BLOCKLIST("blocklist"),

    @Json(name = "whitelist")
    WHITELIST("whitelist"),

    @Json(name = "blacklist")
    BLACKLIST("blacklist"),

    @Json(name = "deliver")
    DELIVER("deliver"),

    @Json(name = "delete")
    DELETE("delete");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PmgQuarantineContentActionEnum) "$data" else null

        /**
         * Returns a valid [PmgQuarantineContentActionEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PmgQuarantineContentActionEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

