/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: BRIDGE,BOND,ETH,ALIAS,VLAN,OVS_BRIDGE,OVS_BOND,OVS_PORT,OVS_INT_PORT,UNKNOWN
 */

@JsonClass(generateAdapter = false)
enum class PmgTypeTypeEnum(val value: kotlin.String) {

    @Json(name = "bridge")
    BRIDGE("bridge"),

    @Json(name = "bond")
    BOND("bond"),

    @Json(name = "eth")
    ETH("eth"),

    @Json(name = "alias")
    ALIAS("alias"),

    @Json(name = "vlan")
    VLAN("vlan"),

    @Json(name = "OVSBridge")
    OVS_BRIDGE("OVSBridge"),

    @Json(name = "OVSBond")
    OVS_BOND("OVSBond"),

    @Json(name = "OVSPort")
    OVS_PORT("OVSPort"),

    @Json(name = "OVSIntPort")
    OVS_INT_PORT("OVSIntPort"),

    @Json(name = "unknown")
    UNKNOWN("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PmgTypeTypeEnum) "$data" else null

        /**
         * Returns a valid [PmgTypeTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PmgTypeTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

