/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentType Raw email header data.
 * @param id Attachment ID
 * @param name Raw email header data.
 * @param propertySize Size of raw attachment in bytes.
 */


data class QuarantineListattachmentsResponseDataInner (

    /* Raw email header data. */
    @Json(name = "content-type")
    val contentType: kotlin.String,

    /* Attachment ID */
    @Json(name = "id")
    val id: kotlin.Long,

    /* Raw email header data. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Size of raw attachment in bytes. */
    @Json(name = "size")
    val propertySize: kotlin.Long

) {


}

