/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param avgbytes Average size of stored mails in bytes.
 * @param count Number of stored mails.
 * @param mbytes Estimated disk space usage in MByte.
 */


data class QuarantineVirusstatusResponseData (

    /* Average size of stored mails in bytes. */
    @Json(name = "avgbytes")
    val avgbytes: java.math.BigDecimal,

    /* Number of stored mails. */
    @Json(name = "count")
    val count: kotlin.Long,

    /* Estimated disk space usage in MByte. */
    @Json(name = "mbytes")
    val mbytes: java.math.BigDecimal

) {


}

