/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bytes Size of raw email.
 * @param content Raw email data (first 4096 bytes). Useful for preview. NOTE: The  'htmlmail' formatter displays the whole email.
 * @param envelopeSender SMTP envelope sender.
 * @param from Header 'From' field.
 * @param header Raw email header data.
 * @param id Unique ID
 * @param `receiver` Receiver email address
 * @param spaminfo Information about matched spam tests (name, score, desc, url).
 * @param spamlevel Spam score.
 * @param subject Header 'Subject' field.
 * @param time Receive time stamp
 * @param sender Header 'Sender' field.
 */


data class QuarantineContentContentResponseData (

    /* Size of raw email. */
    @Json(name = "bytes")
    val bytes: kotlin.Long,

    /* Raw email data (first 4096 bytes). Useful for preview. NOTE: The  'htmlmail' formatter displays the whole email. */
    @Json(name = "content")
    val content: kotlin.String,

    /* SMTP envelope sender. */
    @Json(name = "envelope_sender")
    val envelopeSender: kotlin.String,

    /* Header 'From' field. */
    @Json(name = "from")
    val from: kotlin.String,

    /* Raw email header data. */
    @Json(name = "header")
    val header: kotlin.String,

    /* Unique ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* Receiver email address */
    @Json(name = "receiver")
    val `receiver`: kotlin.String,

    /* Information about matched spam tests (name, score, desc, url). */
    @Json(name = "spaminfo")
    val spaminfo: kotlin.collections.List<kotlin.Any>,

    /* Spam score. */
    @Json(name = "spamlevel")
    val spamlevel: java.math.BigDecimal,

    /* Header 'Subject' field. */
    @Json(name = "subject")
    val subject: kotlin.String,

    /* Receive time stamp */
    @Json(name = "time")
    val time: kotlin.Long,

    /* Header 'Sender' field. */
    @Json(name = "sender")
    val sender: kotlin.String? = null

) {


}

