/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgQuarantineContentActionEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param action Action - specify what you want to do with the mail.
 * @param id Unique IDs, separate with ;
 */


data class QuarantineContentActionRequest (

    /* Action - specify what you want to do with the mail. */
    @Json(name = "action")
    val action: PmgQuarantineContentActionEnum,

    /* Unique IDs, separate with ; */
    @Json(name = "id")
    val id: kotlin.String

) {


}

