/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bouncesIn Incoming bounce mail count (sender = <>).
 * @param bouncesOut Outgoing bounce mail count (sender = <>).
 * @param count Overall mail count (in and out).
 * @param countIn Incoming mail count.
 * @param countOut Outgoing mail count.
 * @param index Time index.
 * @param pregreetRejects PREGREET reject count.
 * @param rblRejects Number of RBL rejects.
 * @param spamcountIn Incoming spam mails (spamcount_in + glcount + spfcount + rbl_rejects + pregreet_rejects).
 * @param spamcountOut Outgoing spam mails.
 * @param time Time (Unix epoch).
 * @param viruscountIn Number of incoming virus mails.
 * @param viruscountOut Number of outgoing virus mails.
 */


data class StatisticsMailcountResponseDataInner (

    /* Incoming bounce mail count (sender = <>). */
    @Json(name = "bounces_in")
    val bouncesIn: java.math.BigDecimal,

    /* Outgoing bounce mail count (sender = <>). */
    @Json(name = "bounces_out")
    val bouncesOut: java.math.BigDecimal,

    /* Overall mail count (in and out). */
    @Json(name = "count")
    val count: java.math.BigDecimal,

    /* Incoming mail count. */
    @Json(name = "count_in")
    val countIn: java.math.BigDecimal,

    /* Outgoing mail count. */
    @Json(name = "count_out")
    val countOut: java.math.BigDecimal,

    /* Time index. */
    @Json(name = "index")
    val index: kotlin.Long,

    /* PREGREET reject count. */
    @Json(name = "pregreet_rejects")
    val pregreetRejects: kotlin.Long,

    /* Number of RBL rejects. */
    @Json(name = "rbl_rejects")
    val rblRejects: kotlin.Long,

    /* Incoming spam mails (spamcount_in + glcount + spfcount + rbl_rejects + pregreet_rejects). */
    @Json(name = "spamcount_in")
    val spamcountIn: java.math.BigDecimal,

    /* Outgoing spam mails. */
    @Json(name = "spamcount_out")
    val spamcountOut: java.math.BigDecimal,

    /* Time (Unix epoch). */
    @Json(name = "time")
    val time: kotlin.Long,

    /* Number of incoming virus mails. */
    @Json(name = "viruscount_in")
    val viruscountIn: java.math.BigDecimal,

    /* Number of outgoing virus mails. */
    @Json(name = "viruscount_out")
    val viruscountOut: java.math.BigDecimal

) {


}

