/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models

import com.clientapi.pmg.models.PmgBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blocked Mail was blocked.
 * @param bytes Mail traffic (Bytes).
 * @param spamlevel Spam score.
 * @param time Receive time stamp
 * @param `receiver` Receiver email. (for sender statistics)
 * @param sender Sender email. (for contact and receiver statistics)
 * @param virusinfo Virus name.
 */


data class StatisticsDetailstatsResponseDataInner (

    /* Mail was blocked. */
    @Json(name = "blocked")
    val blocked: PmgBoolean,

    /* Mail traffic (Bytes). */
    @Json(name = "bytes")
    val bytes: java.math.BigDecimal,

    /* Spam score. */
    @Json(name = "spamlevel")
    val spamlevel: java.math.BigDecimal,

    /* Receive time stamp */
    @Json(name = "time")
    val time: kotlin.Long,

    /* Receiver email. (for sender statistics) */
    @Json(name = "receiver")
    val `receiver`: kotlin.String? = null,

    /* Sender email. (for contact and receiver statistics) */
    @Json(name = "sender")
    val sender: kotlin.String? = null,

    /* Virus name. */
    @Json(name = "virusinfo")
    val virusinfo: kotlin.String? = null

) {


}

