/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bytes Mail traffic (Bytes).
 * @param sender Sender email.
 * @param count Mail count.
 * @param viruscount Number of sent virus mails.
 */


data class StatisticsSenderResponseDataInner (

    /* Mail traffic (Bytes). */
    @Json(name = "bytes")
    val bytes: java.math.BigDecimal,

    /* Sender email. */
    @Json(name = "sender")
    val sender: kotlin.String,

    /* Mail count. */
    @Json(name = "count")
    val count: java.math.BigDecimal? = null,

    /* Number of sent virus mails. */
    @Json(name = "viruscount")
    val viruscount: java.math.BigDecimal? = null

) {


}

