/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count Detection count.
 * @param level Spam level.
 * @param ratio Portion of overall mail count.
 */


data class StatisticsSpamscoresResponseDataInner (

    /* Detection count. */
    @Json(name = "count")
    val count: kotlin.Long,

    /* Spam level. */
    @Json(name = "level")
    val level: kotlin.String,

    /* Portion of overall mail count. */
    @Json(name = "ratio")
    val ratio: java.math.BigDecimal

) {


}

