/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param avptime Average mail processing time in seconds.
 * @param bouncesIn Incoming bounce mail count (sender = <>).
 * @param bouncesOut Outgoing bounce mail count (sender = <>).
 * @param bytesIn Incoming mail traffic (bytes).
 * @param bytesOut Outgoing mail traffic (bytes).
 * @param count Overall mail count (in and out).
 * @param countIn Incoming mail count.
 * @param countOut Outgoing mail count.
 * @param glcount Number of greylisted mails.
 * @param junkIn Incoming junk mail count (viruscount_in + spamcount_in + glcount + spfcount + rbl_rejects + pregreet_rejects).
 * @param junkOut Outgoing junk mail count (viruscount_out + spamcount_out).
 * @param pregreetRejects PREGREET reject count.
 * @param rblRejects Number of RBL rejects.
 * @param spamcountIn Incoming spam mails.
 * @param spamcountOut Outgoing spam mails.
 * @param spfcount Mails rejected by SPF.
 * @param viruscountIn Number of incoming virus mails.
 * @param viruscountOut Number of outgoing virus mails.
 */


data class StatisticsMailResponseData (

    /* Average mail processing time in seconds. */
    @Json(name = "avptime")
    val avptime: java.math.BigDecimal,

    /* Incoming bounce mail count (sender = <>). */
    @Json(name = "bounces_in")
    val bouncesIn: java.math.BigDecimal,

    /* Outgoing bounce mail count (sender = <>). */
    @Json(name = "bounces_out")
    val bouncesOut: java.math.BigDecimal,

    /* Incoming mail traffic (bytes). */
    @Json(name = "bytes_in")
    val bytesIn: java.math.BigDecimal,

    /* Outgoing mail traffic (bytes). */
    @Json(name = "bytes_out")
    val bytesOut: java.math.BigDecimal,

    /* Overall mail count (in and out). */
    @Json(name = "count")
    val count: java.math.BigDecimal,

    /* Incoming mail count. */
    @Json(name = "count_in")
    val countIn: java.math.BigDecimal,

    /* Outgoing mail count. */
    @Json(name = "count_out")
    val countOut: java.math.BigDecimal,

    /* Number of greylisted mails. */
    @Json(name = "glcount")
    val glcount: java.math.BigDecimal,

    /* Incoming junk mail count (viruscount_in + spamcount_in + glcount + spfcount + rbl_rejects + pregreet_rejects). */
    @Json(name = "junk_in")
    val junkIn: java.math.BigDecimal,

    /* Outgoing junk mail count (viruscount_out + spamcount_out). */
    @Json(name = "junk_out")
    val junkOut: java.math.BigDecimal,

    /* PREGREET reject count. */
    @Json(name = "pregreet_rejects")
    val pregreetRejects: kotlin.Long,

    /* Number of RBL rejects. */
    @Json(name = "rbl_rejects")
    val rblRejects: kotlin.Long,

    /* Incoming spam mails. */
    @Json(name = "spamcount_in")
    val spamcountIn: java.math.BigDecimal,

    /* Outgoing spam mails. */
    @Json(name = "spamcount_out")
    val spamcountOut: java.math.BigDecimal,

    /* Mails rejected by SPF. */
    @Json(name = "spfcount")
    val spfcount: java.math.BigDecimal,

    /* Number of incoming virus mails. */
    @Json(name = "viruscount_in")
    val viruscountIn: java.math.BigDecimal,

    /* Number of outgoing virus mails. */
    @Json(name = "viruscount_out")
    val viruscountOut: java.math.BigDecimal

) {


}

