/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pmg.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param release The current installed Proxmox Mailgateway Release
 * @param repoid The short git commit hash ID from which this version was build
 * @param version The current installed pmg-api package version
 */


data class VersionVersionResponseData (

    /* The current installed Proxmox Mailgateway Release */
    @Json(name = "release")
    val release: kotlin.String,

    /* The short git commit hash ID from which this version was build */
    @Json(name = "repoid")
    val repoid: kotlin.String,

    /* The current installed pmg-api package version */
    @Json(name = "version")
    val version: kotlin.String

) {


}

